const CONTENTS_DATA = [
    {"date":"2026-08-23","channel":"기자의 사심터뷰","title":"사심터뷰4 여름특집 (티저)","cast":"전원","vid":"ZWYlC5GSTOs"},
    {"date":"2026-08-22","channel":"유튜브 채널","title":"샘리처드 교수 미국 진출 리센느 만나다? | LA 케이콘","cast":"전원","vid":"6AH2QF3SSXE"},
    {"date":"2026-08-21","channel":"KB금융그룹","title":"콘서트에서 잠들어도 된다고요? 😴 별방수면회 현장 공개🌙 | 별이 부르는 방에 | 소란 X 리센느 X 윤마치 | 4K","cast":"전원","vid":"zgFQ03jXaIo"},
    {"date":"2026-08-21","channel":"KB금융그룹","title":"오늘은 편안하게 쉬어가요🌙 | 별방수면회💤","cast":"전원","vid":"qHT4fR8AW-s"},
    {"date":"2026-08-21","channel":"안녕하세요원이입니다잘부탁드립니다","title":"고윤정을 좋아하세요?","cast":"제나, 리브","vid":"6y_g78FQ3io"},
    {"date":"2026-08-20","channel":"서든어택","title":"원이쌤이 알려주는 서든 21주년! l 2교시 l 서든어택","cast":"원이","vid":"ez6tOkXsIBM"},
    {"date":"2026-08-20","channel":"SBS","title":"🎤 EP.18 #RESCENE | 리센느 피아노 연주 오이쉬~!🎹 청아한 멜로디의 향연, 『프리티걸 연주회』에 초대합니다💌 #UP코노","cast":"원이, 미나미, 제나","vid":"_zTSCOy5iFc"},
    {"date":"2026-08-19","channel":"뉴스1","title":"대세 걸그룹 리센느(RESCENE)가 적극 추천하는 'OOO'?","cast":"전원","vid":"X2d4njKBCC4"},
    {"date":"2026-08-18","channel":"경주시","title":"경주에 누가 돌아왔게~!👑 신라 공주 리센느가 돌아왔지💗","cast":"전원","vid":"QHomm66dhL0"},
    {"date":"2026-08-14","channel":"홍현희","title":"리센느 만나고 왔습니다","cast":"전원","vid":"UbT0kZohE-4"},
    {"date":"2026-08-14","channel":"안녕하세요원이입니다잘부탁드립니다","title":"너 도와주러 온거야","cast":"제나, 메이","vid":"hqSzEdrSpno"},
    {"date":"2026-08-13","channel":"전지적 참견 시점","title":"[전참시 미방분] 새 숙소에서 춤추고 숨바꼭질하고!💃🙈 함께 놀 때 제일 재밌는 리센느! #리센느 #rescene #원이 #미나미 #메이 #리브 #제나","cast":"전원","vid":"E6AGyeG7iT0"},
    {"date":"2026-08-13","channel":"SBS","title":"🎤 EP.17 #RESCENE | 리센느 공주님 납시오~!👸 UP코노 왕국 야-호🏰 잠깐! 셋 중 누가 찐? ✧곤듀력 만렙 TEST✧ 프리티걸 선발대회👑 #UP코노","cast":"원이, 미나미, 제나","vid":"IbDeOSDCEX0"},
    {"date":"2026-08-12","channel":"스톤뮤직","title":"[EN] 리센느 리트와 메트 기세가 좋다! 너도? 나도! | 수석연구회 EP.3 | 리브, 메이, 김재환, 김태래","cast":"리브, 메이","vid":"WKMafz2_9p8"},
    {"date":"2026-08-12","channel":"스톤뮤직","title":"\"안녕하세요 잘 부탁 드립니다!!\" 기세를 끌어올리는 플레이리스트 [수석연구회 PICK! 𝐏𝐥𝐚𝐲𝐥𝐢𝐬𝐭] 'EP.3'｜STONE SEMINAR","cast":"리브, 메이","vid":"9HM7NzhpZ20"},
    {"date":"2026-08-11","channel":"안녕하세요원이입니다잘부탁드립니다","title":"제나야 말 좀 해라!!!!!!!!!!!!!!","cast":"원이, 제나","vid":"WTdyA5N4K0k"},
    {"date":"2026-08-10","channel":"쿠팡플레이","title":"현장 스케치 Day 6ㅣ2026 쿠팡플레이 시리즈","cast":"전원","vid":"T5WiUqlMpbg"},
    {"date":"2026-08-08","channel":"문화방송","title":"[리센느 메이킹 필름 EP.2] 리센느 MBC 아시안게임 홍보대사 촬영 비하인드","cast":"전원","vid":"ifL_zaA58KA"},
    {"date":"2026-08-07","channel":"안녕하세요원이입니다잘부탁드립니다","title":"경주에서 올라온 아이돌","cast":"원이, 제나","vid":"4m9eLr-NofA"},
    {"date":"2026-08-07","channel":"쿠팡플레이","title":"현장 스케치 Day 3ㅣ2026 쿠팡플레이 시리즈","cast":"전원","vid":"A8Ba20oXQUE"},
    {"date":"2026-08-06","channel":"전지적 참견 시점","title":"[전녹시] 전지적 녹화 시점★ 단독 게스트 특집! 완전체 #리센느 #전참시 #전지적참견시점 #원이 #미나미 #제나 #리브 #메이 #rescene #prettygirl","cast":"전원","vid":"Q7rZrdzET94"},
    {"date":"2026-08-06","channel":"유튜브 채널","title":"[4K] RESCENE(리센느) - Runaway | 다독다독콘서트📚","cast":"전원","vid":"q26baBF7Uw8"},
    {"date":"2026-08-06","channel":"서든어택","title":"리센느와 함께하는 21주년 이벤트 특강! l 서든어택","cast":"전원","vid":"F1nzMFdE2Tg"},
    {"date":"2026-08-04","channel":"KCON","title":"[#KCONLA2026] Calling future TEAM RESCENE!","cast":"전원","vid":"7o5Fv2BJCko"},
    {"date":"2026-08-03","channel":"i-dle","title":"'Gimme Dat Love' 음악방송 비하인드 PART 1 [i-talk] #256 | i-dle (아이들)ㅣSUB","cast":"원이, 리브, 미나미","vid":"aXd_iYdv4fM"},
    {"date":"2026-08-03","channel":"대구일보","title":"\"진짜 신라공주들이 나타났다\"… '리센느' 경주 홍보 본격 출격","cast":"전원","vid":"trRWCKMnxXA"},
    {"date":"2026-07-31","channel":"인기가요 끝나면 매점가요","title":"매점 야-호! 랭킹 앞에서 직진 밖에 모르는 🌺💖갸루 마인드🎀✨ 리센느! 빼빼로를 향해 당당하게 걷기💨 #인기가요끝나면매점가요2 EP.14 #RESCENE","cast":"전원","vid":"agdQf7SDOLY"},
    {"date":"2026-07-31","channel":"KCON","title":"[#KCONLA2026] ENJOY K-COLLECTION with RESCENE (리센느)","cast":"전원","vid":"EB6EIFKp8xA"},
    {"date":"2026-07-31","channel":"한국야구위원회","title":"[삼성 vs 롯데] 리센느(RESCENE) 미나미의 팬들의 심장에 LOVE ATTACK💘하는 시구 모먼트🙌 | 7.31 | 크보모먼트 | KBO 야구 하이라이트","cast":"미나미","vid":"fnwr_OVqGxg"},
    {"date":"2026-07-30","channel":"서든어택","title":"서든 야호~! 내랑 같이 서든 할 거제~? l 리센느 l 서든어택","cast":"전원","vid":"hmF6PVJBhrc"},
    {"date":"2026-07-30","channel":"수원시","title":"🎁[RESCENE X 댓글이벤트 ]🎁리브&메이 야구장 출몰 사건! 수원 맛, 명소 뽀개기 #리센느 #리브 #메이 #시구 #시타 #댓글이벤트 #리브바보아니다 #리트 #메트","cast":"리브, 메이","vid":"-gOFiNOSLvw"},
    {"date":"2026-07-30","channel":"박유호","title":"[VLOG] 아니 4살이 리센느 누나들을 이렇게 좋아한다고...? 🫢 헤어지기 싫어서 눈물바다 된 유호 (EN/JP/ID)","cast":"전원","vid":"bEQbeZvA-b8"},
    {"date":"2026-07-29","channel":"THE K-POP 유튜브 프","title":"리센느 음방 퇴근길 복주머니에 뭐가 들어있을까? 오이데 오이데 마떼루용~ | 복주머니 EP.1","cast":"전원","vid":"SbXjaE4Lo3I"},
    {"date":"2026-07-28","channel":"TEO 테오","title":"원이짱 미나미짱 상담하러 교무실로 오이데-★ | EP. 150 리센느 원이 미나미 | 살롱드립","cast":"원이, 미나미","vid":"yq_nZPUBHuU"},
    {"date":"2026-07-28","channel":"유튜브 채널","title":"[LIVE] RESCENE 라이브 모아 듣기 | 우쥬레코드 리센느 편","cast":"미나미, 제나","vid":"7fJ5Bl--GBc"},
    {"date":"2026-07-28","channel":"열혈농구단","title":"[#비하인드]이글스 야호~ 핫한 RESCENE(리센느)의 공연","cast":"전원","vid":"eLg4ZnqYFoE"},
    {"date":"2026-07-28","channel":"kt wiz","title":"어디서나 당당하게 걷기~♬ 리트와 메트 왔어요🎀💖 리센느 리브&메이 시구 비하인드 [위즈티비]","cast":"리브, 메이","vid":"hX82Uz-aTfE"},
    {"date":"2026-07-28","channel":"M2(엠넷)","title":"[LIVE] RESCENE 제나 - 늦은 후회 (원곡: 보보) | 우쥬레코드 리센느 편","cast":"미나미, 제나","vid":"C-wgxpl9GbQ"},
    {"date":"2026-07-28","channel":"M2(엠넷)","title":"[LIVE] RESCENE 미나미&제나 - Pretty Girl | 우쥬레코드 리센느 편","cast":"미나미, 제나","vid":"SjwO7LIyq2Y"},
    {"date":"2026-07-28","channel":"M2(엠넷)","title":"[LIVE] RESCENE 미나미&제나 - 리센느 메들리 (Cotton Candy / New World / Mood / CRASH) | 우쥬레코드 리센느 편","cast":"미나미, 제나","vid":"jgu7AHj1Z9Q"},
    {"date":"2026-07-28","channel":"M2(엠넷)","title":"[LIVE] RESCENE 미나미&제나 - 행복한 나를 (원곡: 에코 (ECO)) | 우쥬레코드 리센느 편","cast":"미나미, 제나","vid":"yZqWUDZbGXY"},
    {"date":"2026-07-26","channel":"유튜브 채널","title":"[우쥬레코드] RESCENE 미나미, 제나 with 윤하 | 혜성, 늦은 후회, 행복한 나를, Pretty Girl | WOULD YOU RECORD (ENG/JPN)","cast":"미나미, 제나","vid":"MbCT-UmVNMw"},
    {"date":"2026-07-25","channel":"잔망루피 Artist 유튜브 ...","title":"🎀리센느 선배님 모셨습니다!💗","cast":"리브, 메이","vid":"W93w7UPevEk"},
    {"date":"2026-07-25","channel":"유튜브 채널","title":"리센느의 쿠팡플레이 시리즈 하프타임 쇼! | 2026 쿠팡플레이 시리즈","cast":"전원","vid":"uWbwYIFeq48"},
    {"date":"2026-07-24","channel":"유튜브 채널","title":"안녕하세요리센느입니다잘부탁드립니다 | 집대성 ep.117 리센느","cast":"전원","vid":"PB_LhQF56S4"},
    {"date":"2026-07-24","channel":"더 쇼","title":"신상 먹으면서 파라파라나 춰야겠다 (feat. 아이돌 총출동) | 신상부스 농심 신상과자 3종 편","cast":"미나미, 제나","vid":"qUSyUUuYVg0"},
    {"date":"2026-07-24","channel":"한국관광공사","title":"거제에서 누가 돌아왔~~게! 리센느 원이의 추천은 계속된다!ㅣEp.07 감동의 거제ㅣ망치몽돌해수욕장, 막썰이회, 지세포진성, 흥남철수기념공원, 밀면, 매미성","cast":"원이","vid":"aUO8cgJGpTk"},
    {"date":"2026-07-23","channel":"Mnet K-POP","title":"'엠카드림' 오늘의 M-Zㅣ니🧞‍♂️ i-dle(아이들), RESCENE(리센느), EVAN(에반) #엠카운트다운 EP.938 | Mnet 260723 방송","cast":"원이, 미나미","vid":"WJVFMKrx4VI"},
    {"date":"2026-07-23","channel":"문화방송","title":"[리센느 메이킹 필름 EP.1] 리센느 MBC 아시안게임 홍보대사 촬영 비하인드","cast":"전원","vid":"R8flNzqcl1Y"},
    {"date":"2026-07-22","channel":"악성 내성인 정일영 유튜브 프...","title":"할아버지와 다섯 손녀들 (리센느 원이, 미나미, 리브, 제나, 메이)","cast":"전원","vid":"3X8KpQiy4uM"},
    {"date":"2026-07-22","channel":"배성재의 TEN","title":"끝까지 깨발랄 리센느 메이 & 리브 ❤ㅋㅋㅋ","cast":"리브, 메이","vid":"9pELuJ8qpww"},
    {"date":"2026-07-22","channel":"전지적 참견 시점","title":"[전참시 미방분] 리센느가 치킨 먹다 눈물 흘린 이유🥹 #리센느 #rescene #비하인드","cast":"전원","vid":"46_rcJZAvGQ"},
    {"date":"2026-07-21","channel":"인생84프로필","title":"리센느의 하루","cast":"전원","vid":"7C9PRXBWWEM"},
    {"date":"2026-07-21","channel":"유튜브 채널","title":"수원에 등장한 리센느 '리트와 메트'! 한 주의 문을 여는 다채로운 시구 모음 | 7.21 | 크보모먼트 | KBO 야구 하이라이트","cast":"리브, 메이","vid":"XRcYeXQHzgQ"},
    {"date":"2026-07-21","channel":"더 쇼","title":"리센느 팬들 앞에서 또 운(?) 이유 [FANPOPTY] EP.2 FULL","cast":"전원","vid":"O3ALEA1dUPc"},
    {"date":"2026-07-21","channel":"Mnet","title":"RESCENE(리센느)가 알려주는 이번 주 엠카운트다운 라인업은? #엠카운트다운 EP.938","cast":"전원","vid":"aPoHgUlXbuw"},
    {"date":"2026-07-20","channel":"현대 N 페스티벌 유튜브 프","title":"현대 N 페스티벌 X 리센느 | 엔페 어택","cast":"전원","vid":"XkvLZw-RRT8"},
    {"date":"2026-07-20","channel":"잔망루피","title":"😍여기 큐티지수 터졌어요💥| 리센느(리브 & 메이)🎤 - 살찌면 더 귀여워 (Cover))","cast":"리브, 메이","vid":"XReBEo6w6us"},
    {"date":"2026-07-18","channel":"잔망루피 Artist 유튜브 ...","title":"✨프리티 걸 보이 모두 컴온💖 | Pretty Girl (원곡: 리센느) - 잔망루피🎤(Cover)","cast":"리브, 메이","vid":"XXtRTxqrjgg"},
    {"date":"2026-07-17","channel":"술 빚는 윤주모","title":"프리티걸 1위 야-호!🎀 얼마나 잘 될지 감도 안 오는 리센느랑 두 번째💖 | 해방토크 EP.16","cast":"리브, 미나미, 제나","vid":"PRGn7LYfLAY"},
    {"date":"2026-07-17","channel":"안녕하세요원이입니다잘부탁드립니다","title":"안원잘부 미방분","cast":"원이","vid":"8r-YPb_tKlM"},
    {"date":"2026-07-16","channel":"솔로몬코드","title":"ヤッホー! 요즘 대세 리센느 만났다!! 광희랑 딱 30분만! EP.03","cast":"전원","vid":"tZis2XexN0g"},
    {"date":"2026-07-16","channel":"유튜브 채널","title":"[#직캠보고서🔍] #RESCENE #리센느 나는 원래 리센느를 사랑해🎀 프리티걸 이름값하는 소녀들이 왔다 음중 사전녹화 비하인드⏯️","cast":"전원","vid":"EkR1LMEWDPc"},
    {"date":"2026-07-16","channel":"카사베르디","title":"RESCENE X CASAVERDI | TV CF 클로즈업 미공개 컷 모음 ZIP","cast":"전원","vid":"UhxSM84Q8mg"},
    {"date":"2026-07-16","channel":"없섭","title":"레이싱하길 잘했다 리센느도 만나고","cast":"전원","vid":"vPUECMr51Tg"},
    {"date":"2026-07-16","channel":"KBS 월드","title":"[아이돌부스 1화] 아니 제발 그만 뽑아줘... 리센느의 도파민 폭주🔥선물뽑기 결말은? [4K] | IDOL Booth Ep 01 #원이 #리브 #미나미 #메이 #제나","cast":"전원","vid":"Hw8KH7RqHQo"},
    {"date":"2026-07-15","channel":"웬정막","title":"[실제상황] 거제도 여행 중에 리센느 만난 욱정수 \"오이쉬이~\"","cast":"전원","vid":"ePNfrlXrxd8"},
    {"date":"2026-07-15","channel":"스튜디오 드리밍","title":"오디션 곡부터 대표곡, 멤버별 최애곡까지... 무려 '24곡' 라이브🫢 리센느 보컬유닛이 노래로 증명하고 갔습니다🎤｜먼키의 발자국👣 EP39. 리센느 (미나미&리브&제나)","cast":"리브, 미나미, 제나","vid":"Kks1mrblGNQ"},
    {"date":"2026-07-14","channel":"유튜브 채널","title":"[In The Studio] RESCENE (리센느) - Pretty Girl｜인더스튜디오, STONE PERFORMANCE","cast":"전원","vid":"mQ4-qhvDoiU"},
    {"date":"2026-07-13","channel":"SBS","title":"7월 2주 차 '이현X원이X미나미' 엠씨 컷 모음🍒🎀🩷 | SBS 인기가요 | SBS","cast":"전원","vid":"4-yicCXfEkk"},
    {"date":"2026-07-13","channel":"전지적 참견 시점","title":"[전참시 미방분] 거제 바다에서 초딩력 max되는 리센느! #리센느 #거제 #리브 #메이","cast":"전원","vid":"X1C8_mrFbZk"},
    {"date":"2026-07-12","channel":"KBS WORLD TV 유튜브...","title":"[3D 아부VR캠] RESCENE(리센느) - Pretty Girl (프리티걸) 8K | IDOL Booth (아이돌부스)","cast":"전원","vid":"deeIxetPU9k"},
    {"date":"2026-07-11","channel":"안녕하세요원이입니다잘부탁드립니다","title":"Endless Rain","cast":"원이","vid":"F5CbMShscuk"},
    {"date":"2026-07-10","channel":"유튜브 채널","title":"나의 계곡 아저씨 선민 삼촌과 함께한 1위 가수 리센느 원이 미나미의 첫 계곡 힐링기🍀 [성수기 스핀오프 EP.2]","cast":"원이, 미나미","vid":"r5oAQkNvMGk"},
    {"date":"2026-07-10","channel":"유튜브 채널","title":"[릴레이댄스] 리센느(RESCENE) - Pretty Girl (4K)","cast":"전원","vid":"AT_coOD7phk"},
    {"date":"2026-07-10","channel":"경주시","title":"경주에서 서울까지 333km… 이 정도면 봐주이소 | 리센느 홍보대사 위촉장 전달 비하인드","cast":"전원","vid":"tikwDegt2nM"},
    {"date":"2026-07-10","channel":"안녕하세요원이입니다잘부탁드립니다","title":"양키의 하루 배워보기 | 캐릭터 외전","cast":"원이, 미나미","vid":"5spDxl-yzUQ"},
    {"date":"2026-07-10","channel":"안녕하세요원이입니다잘부탁드립니다","title":"거제 불주먹 양키","cast":"원이","vid":"qzhjmlxNl8s"},
    {"date":"2026-07-10","channel":"안녕하세요원이입니다잘부탁드립니다","title":"오빻","cast":"원이","vid":"VUufd3Hd_2Q"},
    {"date":"2026-07-10","channel":"윤나라(요리사)","title":"온 세상이 리센느💗 윤주당 최초 아이돌 손님 등장! | 해방토크 EP.15","cast":"리브, 미나미, 제나","vid":"GE8FCHPGLwE"},
    {"date":"2026-07-10","channel":"전지적 참견 시점","title":"[전녹시] 전참시 물들이러 온 리센느! 토요일 밤 11시 10분","cast":"원이, 미나미","vid":"8PmCZ_80tKU"},
    {"date":"2026-07-09","channel":"정다쌤과 아이들","title":"한국 초등학생이 부르는 RESCENE (리센느) - LOVE ATTACK(러브어택) #리센느 #RESCENE #LOVEATTACK#월드컵#한국초등학생 #월드컵","cast":"전원","vid":"Z6AOhgx3VfU"},
    {"date":"2026-07-08","channel":"스타뉴스","title":"리센느(RESCENE) 스타뉴스 인터뷰 \"'프리티걸' 리센느 버전 많이 사랑해주세요\" #리센느 #RESCENE #야호 #카라 #프리티걸 #리메이크","cast":"전원","vid":"prhl5CO-XAU"},
    {"date":"2026-07-08","channel":"유튜브 채널","title":"[💗발매 인사 영상] RESCENE (리센느) - Pretty Girl - Special Single｜STONE MUSIC+","cast":"전원","vid":"JmAbPrgSQMQ"},
    {"date":"2026-07-08","channel":"경기도교육청","title":"오늘은 아이돌 말고 학교쌤!(feat. 리센느 원이)｜쌤이되려GO EP.01｜양영디지털고등학교ㅣ 경기도교육청","cast":"원이","vid":"lmwmyN3XFtM"},
    {"date":"2026-07-08","channel":"KBS WORLD TV 유튜브...","title":"[아부캠 첫공개] RESCENE(리센느) - Pretty Girl (프리티걸) [4K] | IDOL Booth (아이돌부스)","cast":"전원","vid":"QhZ70uPT8P8"},
    {"date":"2026-07-08","channel":"스튜디오 슷슷","title":"[Eng Sub] 입덕프로필 RESCENE 리센느 편 | 안녕하세요리센느입덕프로필입니다잘부탁드립니다💖 너도? 나도!👍 오이쉬✨한 리센느 입덕프로필💕 #RESCENE #리센느","cast":"전원","vid":"BuN4QpfO5l0"},
    {"date":"2026-07-07","channel":"유병재 유튜브 채널","title":"[무겜딱] 겁이 없어도 너무 없는 아이돌과..ㅠ (w.리센느 원이, 미나미)","cast":"원이, 미나미","vid":"pxrPEZXadVc"},
    {"date":"2026-07-07","channel":"스포티비뉴스","title":"[위클리상암 초대석] 리센느, 밈의 지옥에 빠졌다?│위클리상암 (26.07.07)","cast":"전원","vid":"NkkZRWGnWCE"},
    {"date":"2026-07-07","channel":"카사베르디","title":"첫 TV CF 메이킹 & 서프라이즈 이벤트 비하인드 | 리센느 X 카사베르디","cast":"전원","vid":"rxoGhCuz_4w"},
    {"date":"2026-07-06","channel":"엠넷플러스 심볼","title":"[Tingle Room/6회] 🎀프리티걸🎀이 직접 먹여주는 감기약? 오이시!","cast":"미나미","vid":"oZj1hhA3PTE"},
    {"date":"2026-07-06","channel":"엠넷플러스","title":"[Tingle Room/6회] 감기 걸렸다고? 갸루 짝꿍 미나미가 다 낫게 해줄게ᯓ★","cast":"미나미","vid":"X2UF2YQCZ7w"},
    {"date":"2026-07-06","channel":"션(지누션))","title":"리센느 음원 차트 3위라고? 메이 어딨어?","cast":"메이","vid":"GACUxFNJMsg"},
    {"date":"2026-07-04","channel":"안녕하세요원이입니다잘부탁드립니다","title":"좋지 않아?","cast":"원이","vid":"tDs3mcabrFM"},
    {"date":"2026-07-04","channel":"안녕하세요원이입니다잘부탁드립니다","title":"새로운 등교 친구","cast":"원이","vid":"FxbR-V8GOjE"},
    {"date":"2026-07-04","channel":"안녕하세요원이입니다잘부탁드립니다","title":"센빠이!","cast":"원이","vid":"4ciHuGLi_1I"},
    {"date":"2026-07-04","channel":"안녕하세요원이입니다잘부탁드립니다","title":"원이의 꿈","cast":"원이","vid":"jilQNKreZBM"},
    {"date":"2026-07-03","channel":"한국관광공사TV","title":"거제↗가면↘밥은↗줍니까? 밥도 주고 바다도 보여주는 리센느 원이픽🎯거제 코스ㅣEp.06 거제 야호 | 외도 보타니아, 해금강 십자동굴, 와현해수욕장, 거제 맛집","cast":"원이","vid":"YV9Q9fBNzLs"},
    {"date":"2026-07-03","channel":"나의 연수 아저씨","title":"원이, 편안함에 이르렀나 | 나의연수아저씨 졸업식","cast":"전원","vid":"paJ8svJ1IoE"},
    {"date":"2026-07-03","channel":"안녕하세요원이입니다잘부탁드립니다","title":"미나미의 뿌리를 찾아서 | 최종화","cast":"원이, 미나미","vid":"Yy58f1A6F-c"},
    {"date":"2026-07-01","channel":"유튜브 채널","title":"📞RESCENE 미나미 – Still With You (원곡: 정국) | 여보세요? EP.5","cast":"미나미","vid":"DWfTD9f3Z2A"},
    {"date":"2026-07-01","channel":"디스패치","title":"[EXCLUSIVE] 리센느 성격 테스트 EP.3 ✍️ -스티커 코어 테스트 편-","cast":"리브, 메이, 제나","vid":"ijMnpXovnXY"},
    {"date":"2026-07-01","channel":"디스패치","title":"[EXCLUSIVE] 리센느 성격 테스트 풀버전","cast":"리브, 메이, 제나","vid":"Bbp76jmUvh4"},
    {"date":"2026-07-01","channel":"효연의 레벨업","title":"[ENG] 워니 미나미쨩~ 효여니가 진짜루 이빠이 아이시떼루 / 가짜 김효연 EP.24 갸루 편 (리센느 원이, 미나미)","cast":"원이, 미나미","vid":"zMIGR797Wtc"},
    {"date":"2026-06-29","channel":"동네친구 강나미","title":"[MV] 태연 (TAEYEON)_ 만찬가 (晩餐歌 / BANSANKA) : J-POP REMAKE Vol.1","cast":"원이, 미나미","vid":"H0GbvPY_Yl8"},
    {"date":"2026-06-29","channel":"안녕하세요원이입니다잘부탁드립니다","title":"장롱에 누군가 있다","cast":"원이","vid":"y2TOOxHF35E"},
    {"date":"2026-06-29","channel":"안녕하세요원이입니다잘부탁드립니다","title":"고멘네!","cast":"원이","vid":"GUHzPMtxAqY"},
    {"date":"2026-06-29","channel":"안녕하세요원이입니다잘부탁드립니다","title":"서예하는 미나미","cast":"원이","vid":"5qmyo1nR3no"},
    {"date":"2026-06-28","channel":"디스패치","title":"[EXCLUSIVE] 리센느 성격 테스트 EP.2 ✍️ -내적나이 테스트 편-","cast":"리브, 메이, 제나","vid":"G1qrv_CCyeY"},
    {"date":"2026-06-28","channel":"뮤니버스","title":"📞EP.5 미나미(MINAMI) 비하인드 RETRO VER | 여보세요?","cast":"미나미","vid":"xLMHRrA0J8U"},
    {"date":"2026-06-28","channel":"안녕하세요원이입니다잘부탁드립니다","title":"미나미의 본모습","cast":"원이, 미나미","vid":"wdH5_I7UiHA"},
    {"date":"2026-06-27","channel":"꼰대희","title":"[밥묵자]부산호소인 사투리 고치러 온 거제소녀와 신라공주(feat. 리센느 원이, 제나)","cast":"원이, 제나","vid":"VsdN3ZM9fvA"},
    {"date":"2026-06-27","channel":"뮤니버스","title":"📞EP.5 미나미(MINAMI) 비하인드 | 여보세요?)","cast":"미나미","vid":"7RWYsbErDJE"},
    {"date":"2026-06-27","channel":"안녕하세요원이입니다잘부탁드립니다","title":"쪽팔려게임","cast":"원이","vid":"beKjAiS8n44"},
    {"date":"2026-06-26","channel":"스튜디오ㅋㅇㅋ","title":"성공한 원이가 사주는 특별한 선물","cast":"원이","vid":"eUHfCCP1AsU"},
    {"date":"2026-06-26","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갑자기 떡상해서 찍는 댓글읽기","cast":"원이, 리브, 메이","vid":"xYLNDE4RXsg"},
    {"date":"2026-06-26","channel":"카사베르디","title":"🎥 리센느X카사베르디 TVCF 메이킹 필름 I RESCENE X CASA VERDI MAKING FILM","cast":"전원","vid":"9i1cbplzxQM"},
    {"date":"2026-06-25","channel":"디스패치","title":"[EXCLUSIVE] 리센느 미나미&원이의 ASMR 야-호 EP.3","cast":"원이, 미나미","vid":"Is9G26gRqjg"},
    {"date":"2026-06-24","channel":"동네친구 강나미","title":"[MV teaser] 태연 (TAEYEON)_ 만찬가 (晩餐歌 / BANSANKA) : J-POP REMAKE Vol.1","cast":"원이, 미나미","vid":"6xunrScz_5k"},
    {"date":"2026-06-24","channel":"안녕하세요원이입니다잘부탁드립니다","title":"첫TVCF입니다잘부탁드립니다","cast":"원이","vid":"Gnf3QzdopbM"},
    {"date":"2026-06-24","channel":"거제시","title":"거제시정뉴스 6월 1주차 / 거제 야-호!! 리센느 거제시청 방문 및 마케팅 일정 소화","cast":"전원","vid":"AsSo48oCsj8"},
    {"date":"2026-06-23","channel":"ALL THE K-POP","title":"[아언플 모음.zip] RESCENE 무대부터 비하인드까지! 민나 오이데~⭐","cast":"전원","vid":"fvKhUXxe9vE"},
    {"date":"2026-06-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"일본에서 먹히는 발음","cast":"원이","vid":"cDDORzB-2Q0"},
    {"date":"2026-06-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갸루 팩트체크","cast":"원이","vid":"LVr2R5_TFME"},
    {"date":"2026-06-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"혹시 한국인이세요?","cast":"원이","vid":"YDCgJIvro-4"},
    {"date":"2026-06-19","channel":"디스패치","title":"[EXCLUSIVE] 리센느 미나미&원이의 ASMR 야-호 EP.2","cast":"원이, 미나미","vid":"94HN0dQmUB8"},
    {"date":"2026-06-19","channel":"안녕하세요원이입니다잘부탁드립니다","title":"진짜 '야호'하는지 물어봤습니다","cast":"원이, 미나미","vid":"XD3rCGvMPJE"},
    {"date":"2026-06-19","channel":"경인방송 ON AIR 유튜브 ...","title":"[4K] RESCENE(리센느) - Deja Vu | 다독다독콘서트📚","cast":"전원","vid":"5iXutDkOIUw"},
    {"date":"2026-06-18","channel":"디스패치","title":"[EXCLUSIVE] 리센느 성격 테스트 EP.1 ✍️ -조선시대 직업 테스트 편-","cast":"리브, 메이, 제나","vid":"t11Hd5_h8ks"},
    {"date":"2026-06-18","channel":"경인방송 ON AIR 유튜브 ...","title":"[4K] RESCENE(리센느) - Bloom | 다독다독콘서트📚","cast":"전원","vid":"Pikj21NppvY"},
    {"date":"2026-06-18","channel":"김장훈","title":"안녕하세요숲입니다잘부탁드립니다","cast":"원이, 미나미, 제나","vid":"mPgSSBVwEo"},
    {"date":"2026-06-17","channel":"위문열차","title":"백스테이지 CAM - 리센느 [위문열차] @kfnplus","cast":"전원","vid":"zxsBrZA0QZU"},
    {"date":"2026-06-17","channel":"안녕하세요원이입니다잘부탁드립니다","title":"리센느의 월드컵 응원법","cast":"원이","vid":"5zg26mxu4_w"},
    {"date":"2026-06-16","channel":"왕구랜드","title":"하동 녹차밭 급습한 퍼스트 펭귄 이선민 & 서드 펭귄 유영우 🐧 [이선민 & 유영우] | 수확행 EP1","cast":"원이, 리브","vid":"bW6G9EN_tpU"},
    {"date":"2026-06-16","channel":"경인방송 ON AIR 유튜브 ...","title":"[4K] RESCENE(리센느) - LOVE ATTCK | ㅣ다독다독콘서트📚","cast":"전원","vid":"z0L7SJBjNw4"},
    {"date":"2026-06-15","channel":"존이냐박이냐","title":"LOVE ATTACK (존박 ver.)","cast":"전원","vid":"y1SL3LBCGWg"},
    {"date":"2026-06-14","channel":"침착맨","title":"지방인이 무조건 긁히는 순간 월드컵 (with 리센느 원이 & 미나미)","cast":"원이, 미나미","vid":"z9pVFFikowI"},
    {"date":"2026-06-13","channel":"존이냐박이냐","title":"리센느와 멜론 1위 기우제 지냈습니다","cast":"전원","vid":"TerU2JparyE"},
    {"date":"2026-06-12","channel":"그냥 이미주 프로필","title":"갸루 선배랑 파라파라나 춰야겠다 I 리센느 미나미","cast":"미나미","vid":"LuCCfrjKD_Q"},
    {"date":"2026-06-12","channel":"디스패치","title":"[EXCLUSIVE] 신라공주의 여심사냥꾼 최성곤 인터뷰 🌹","cast":"제나","vid":"t11Hd5_h8ks"},
    {"date":"2026-06-12","channel":"안녕하세요원이입니다잘부탁드립니다","title":"저희도 리센느입니다...","cast":"전원","vid":"5JZ5biQ_hMI"},
    {"date":"2026-06-12","channel":"안녕하세요원이입니다잘부탁드립니다","title":"피피엘 뺏겨서 화난 갸루","cast":"원이","vid":"ORksT1QDf3k"},
    {"date":"2026-06-12","channel":"안녕하세요원이입니다잘부탁드립니다","title":"우리도 리센느야","cast":"원이","vid":"P5GHz5HW9Uk"},
    {"date":"2026-06-11","channel":"왕구랜드","title":"거제의 딸 원이가 인정한 거제 핫플 풀코스 여행 🚗 [원이 & 미나미] | 절친소 EP1","cast":"원이, 미나미","vid":"_GKSineBozo"},
    {"date":"2026-06-11","channel":"태양","title":"QUINT:ESSENCE CHALLENGE BEHIND THE SCENES | TAEYANG","cast":"원이, 미나미","vid":"0UgIfTuoqOs"},
    {"date":"2026-06-11","channel":"침착맨","title":"리센느 원이 & 미나미 초대석","cast":"원이, 미나미","vid":"wbfy9Tm0UjA"},
    {"date":"2026-06-11","channel":"침착맨","title":"난 저스트댄스나 춰야겠다","cast":"원이, 미나미","vid":"2usNtJUdtSQ"},
    {"date":"2026-06-10","channel":"팬더원","title":"OFF Air☕ | 결방이지만 또 보고 싶은 오프에어 미방영분입니다🧋","cast":"전원","vid":"0wUiVwubg7k"},
    {"date":"2026-06-10","channel":"팬더원","title":"OFF Air☕ | 결방이지만 또 보고 싶은 오프에어 미방영분입니다🧋","cast":"전원","vid":"0wUiVwubg7k&t=606"},
    {"date":"2026-06-08","channel":"디스패치","title":"[EXCLUSIVE] 리센느 미나미&원이의 ASMR 야-호 EP.1","cast":"원이, 미나미","vid":"I0JzyK2eTzI"},
    {"date":"2026-06-06","channel":"경인방송","title":"[2026년 다독다독북콘서트 2회] 남궁인 작가 , 병점고등학교 , 리센느","cast":"전원","vid":"ApxYtJl-qek"},
    {"date":"2026-06-05","channel":"스튜디오ㅋㅇㅋ","title":"비 오는 날 초보운전이 운전하면 생기는 일","cast":"원이","vid":"LTmcHWbUcBw"},
    {"date":"2026-06-05","channel":"국가유산청 국 상하","title":"[국가유산 상생정책] 수원 야호 붐 올 때까지 파라파라나 춰야겠다..⭐(w.리센느 원이, 리브))","cast":"원이, 리브","vid":"3kzZaHU72Ps"},
    {"date":"2026-06-05","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갸루와 거제 2편","cast":"원이, 미나미","vid":"SF29doLuBfc"},
    {"date":"2026-06-05","channel":"안녕하세요원이입니다잘부탁드립니다","title":"학창시절 인기","cast":"원이","vid":"OmjUI2EQiPw"},
    {"date":"2026-06-05","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갸루 귀신","cast":"원이","vid":"6cPEEeEAKiM"},
    {"date":"2026-06-05","channel":"유튜브 채널","title":"[아이돌 펌프왕 Special Clip] 거제 파이리 🔥원이와 치바 갸루💄 미나미가 펌프하다가 사과드립니다🙇‍♀️🙏","cast":"전원","vid":"rhy2Ko6LRwY"},
    {"date":"2026-06-04","channel":"유튜브 채널","title":"거제 야호가 문특에 왔습니다 (w. 리센느 원이, 미나미, 제나)","cast":"원이, 미나미, 제나","vid":"17t9izNAYVE"},
    {"date":"2026-06-04","channel":"안녕하세요원이입니다잘부탁드립니다","title":"백룸에 갇힌 미나미","cast":"원이","vid":"XJQMnwcMvcw"},
    {"date":"2026-06-01","channel":"위문열차","title":"리센느 ☆ KFN 위문열차","cast":"전원","vid":"ixyiX8s5fvs"},
    {"date":"2026-06-01","channel":"안녕하세요원이입니다잘부탁드립니다","title":"미나미의 볼터치교실 (Feat. 미숫갸루)","cast":"원이","vid":"510hBsWhh0A"},
    {"date":"2026-05-30","channel":"안녕하세요원이입니다잘부탁드립니다","title":"고윤정이 2명","cast":"원이","vid":"gRESmZMqlFA"},
    {"date":"2026-05-30","channel":"안녕하세요원이입니다잘부탁드립니다","title":"내리온나!!!","cast":"원이","vid":"hrFWuCyHXpY"},
    {"date":"2026-05-30","channel":"안녕하세요원이입니다잘부탁드립니다","title":"저한테 왜 그러시는 거예요","cast":"원이","vid":"nHY4EK0kVH0"},
    {"date":"2026-05-29","channel":"스튜디오ㅋㅇㅋ","title":"전여친 결혼식에 타고 간다면 테슬라 모델Y 주니퍼 vs 기아 EV6 GT Line","cast":"원이","vid":"I-NAFhupR1s"},
    {"date":"2026-05-29","channel":"안녕하세요원이입니다잘부탁드립니다","title":"떡상 전 성수나들이 (사투리2편)","cast":"원이, 제나","vid":"JJBf0jCcfrQ"},
    {"date":"2026-05-29","channel":"안녕하세요원이입니다잘부탁드립니다","title":"선크림 발랐는지 모릅니데이","cast":"원이","vid":"PiKBQ65QE1g"},
    {"date":"2026-05-29","channel":"안녕하세요원이입니다잘부탁드립니다","title":"뒤올","cast":"원이","vid":"IQ4MGDgdr5I"},
    {"date":"2026-05-29","channel":"안녕하세요원이입니다잘부탁드립니다","title":"SNS를 해야 알지","cast":"원이","vid":"yFyk6KPsGuA"},
    {"date":"2026-05-29","channel":"안녕하세요원이입니다잘부탁드립니다","title":"우리 연예인 다 됐노","cast":"원이","vid":"xsNWeKpL5IQ"},
    {"date":"2026-05-25","channel":"안녕하세요원이입니다잘부탁드립니다","title":"오늘은생일입니다잘부탁드립니다","cast":"원이","vid":"m-MBLSS70x0"},
    {"date":"2026-05-24","channel":"안녕하세요원이입니다잘부탁드립니다","title":"고향의 좋은 점","cast":"원이","vid":"8u4vD5IwZQc"},
    {"date":"2026-05-24","channel":"안녕하세요원이입니다잘부탁드립니다","title":"시부야 별거 없네","cast":"원이","vid":"PfQMw8-ZAtY"},
    {"date":"2026-05-23","channel":"안녕하세요원이입니다잘부탁드립니다","title":"물고기 물고기 오이데","cast":"원이","vid":"Djc2pShwxpI"},
    {"date":"2026-05-23","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갸루의 건배","cast":"원이","vid":"jcjUlRUDya4"},
    {"date":"2026-05-22","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갸루와 거제에 왔습니다 (거제 1편)","cast":"원이, 미나미","vid":"OrCOflk2QmQ"},
    {"date":"2026-05-21","channel":"제일건강합니다 2","title":"갸루 출신 미나미가 전생 최면 중에 오열한 이유 | 제일건강원 EP.03","cast":"미나미","vid":"s4plNAZfBZc"},
    {"date":"2026-05-18","channel":"KCON","title":"⭐PRESHOW I RESCENE | KCON JAPAN 2026","cast":"전원","vid":"M4N1mylLjEY"},
    {"date":"2026-05-15","channel":"ootb STUDIO 유튜브 ...","title":"전주의 아들이 추천하는 전주 1등 맛집🍚 (feat.리센느 원이,미나미) | 인기 맛집 | 곽범 [EN/JP]","cast":"원이, 미나미","vid":"Kw_x_EcgCLU"},
    {"date":"2026-05-15","channel":"코인없는 코인 노래방 유튜브 ...","title":"리센느 노래방 라이브.zip 📂 LOVE ATTACK(러브어택)부터 Runaway까지 | 코없코 플레이리스트","cast":"전원","vid":"K55zh_anKs4"},
    {"date":"2026-05-15","channel":"뉴스엔미디어","title":"이건 진짜 입덕 영상이다… 리센느 화보 현장 대공개✨ #astar1 #atstyle #RESCENE #리센느 #화보 #비하인드","cast":"전원","vid":"Sn44BKHpm94"},
    {"date":"2026-05-15","channel":"나의 연수 아저씨","title":"원이만 빼고 전기차 캠핑가기","cast":"전원","vid":"2S15hwuwMuA"},
    {"date":"2026-05-15","channel":"안녕하세요원이입니다잘부탁드립니다","title":"선배지만 친구가 하고 싶어","cast":"원이","vid":"TpajmJJlHSE"},
    {"date":"2026-05-14","channel":"KCON","title":"⭐X STAGE I SHOWCASE I RESCENE | KCON JAPAN 2026","cast":"전원","vid":"IyW8UAmKSLs"},
    {"date":"2026-05-08","channel":"스튜디오ㅋㅇㅋ","title":"레이 버리고 제네시스 G80으로 갈아탄 초보운전","cast":"원이","vid":"TuBlsrL8HDE"},
    {"date":"2026-05-08","channel":"안녕하세요원이입니다잘부탁드립니다","title":"미나미에게 위협을 느끼나요? | 10만 기념 Q&A","cast":"원이, 미나미, 제나","vid":"_AqXSSQ0Cmo"},
    {"date":"2026-05-06","channel":"팬더원","title":"OFF Air☕ | 끌어당겨 넌 Now I run away🏃🏻리센느와의 𝐓𝐀𝐋𝐊","cast":"전원","vid":"daNXoYd3w_w"},
    {"date":"2026-05-06","channel":"팬더원","title":"OFF Air☕ BEHIND | 돌아서 난 이미 어서 Hold my hand🤝리센느 𝘾𝙐𝙏","cast":"전원","vid":"oXUCpdqFfOQ"},
    {"date":"2026-05-03","channel":"안녕하세요원이입니다잘부탁드립니다","title":"이거 큰일난거 아이가?","cast":"원이","vid":"QQmGNdNgs8w"},
    {"date":"2026-05-03","channel":"안녕하세요원이입니다잘부탁드립니다","title":"졸리는건 목 입니다","cast":"원이","vid":"QEpr_lLWw-0"},
    {"date":"2026-05-03","channel":"안녕하세요원이입니다잘부탁드립니다","title":"애정넘치는 대화입니다","cast":"원이","vid":"c8vCVztYVg8"},
    {"date":"2026-05-02","channel":"안녕하세요원이입니다잘부탁드립니다","title":"블루베리스무디 못 시키는 이유","cast":"원이","vid":"M-UsuPm7zcM"},
    {"date":"2026-05-02","channel":"안녕하세요원이입니다잘부탁드립니다","title":"선크림 그거 와바르노?","cast":"원이","vid":"Fxc1_HkGlBw"},
    {"date":"2026-05-02","channel":"안녕하세요원이입니다잘부탁드립니다","title":"니 살림차리고 싶나?","cast":"원이","vid":"JFpNSb2pqLQ"},
    {"date":"2026-05-01","channel":"벨리곰 TV","title":"갸루 출신 일본인에게 대전 빵투어를 시켜준다면? (feat. 대전 빵택시)","cast":"원이, 미나미","vid":"yMeBhxSGvVw"},
    {"date":"2026-05-01","channel":"나의 연수 아저씨","title":"홍박사로 대박난 조훈이 BMW X5 사러 왔습니다 | 중고생 EP.05","cast":"전원","vid":"iLBc6SQJYZU"},
    {"date":"2026-05-01","channel":"안녕하세요원이입니다잘부탁드립니다","title":"하루종일 사투리만 써봤습니다","cast":"원이, 미나미, 제나","vid":"NS7tSrMrWsc"},
    {"date":"2026-05-01","channel":"it's Live","title":"[아이돌 펌프왕] Q. 혹시 갸루✨도 ’펌프‘를 하나요? A. RESCENE : 에? 멧챠 무리🥵 그래도 펌프왕은 야호♥️ (IDOL PUMP KING EP.3-2)","cast":"전원","vid":"3VIW53k6F4Q"},
    {"date":"2026-05-01","channel":"뮤니버스","title":"[아이돌 펌프왕] SANTOS BRAVOS, MODYSSEY, 앰퍼샌드원, 다영, RESCENE (IDOL PUMP KING EP.3-2)","cast":"전원","vid":"2c4yKRw3LiI&t=1371s"},
    {"date":"2026-04-29","channel":"세이프K","title":"리센느와 함께 알아보는 다중 운집 인파사고 대처법","cast":"전원","vid":"hlWXwS4q1Jk"},
    {"date":"2026-04-28","channel":"SoundBomb360 유튜브...","title":"[Behind: SoundBOMB360˚] 리센느(RESCENE)｜싸운드밤삼육공 비하인드 [SUB]","cast":"전원","vid":"lCdQIZQQqiQ"},
    {"date":"2026-04-27","channel":"SoundBomb360 유튜브...","title":"[8K] PLAYLIST｜리센느(RESCENE) 🎵Runaway｜🎧공간음향｜SoundBOMB360˚","cast":"전원","vid":"evfWfg6jRZc"},
    {"date":"2026-04-27","channel":"SoundBomb360 유튜브...","title":"[8K] PLAYLIST｜리센느(RESCENE) 🎵YoYo｜🎧공간음향｜SoundBOMB360˚","cast":"전원","vid":"fVpFZAOVuk0"},
    {"date":"2026-04-24","channel":"벨리곰 TV","title":"충주맨 없는 충주시에 가면 생기는 일 (feat. 김선태)","cast":"원이","vid":"W0cpLR0rz0Q"},
    {"date":"2026-04-24","channel":"나의 연수 아저씨","title":"삼촌들과 유니폼 입고 떠나는 조기 축구 풀코스 (feat.빨간 레이)","cast":"전원","vid":"fB0bjJB6f6Y"},
    {"date":"2026-04-23","channel":"Mnet K-POP","title":"'엠카드림' 오늘의 M-Zㅣ니🧞‍♂️ RESECENE, KickFlip, KEYVITUP, MODYSSEY #엠카운트다운 EP.925 | Mnet 260423 방송","cast":"원이, 미나미","vid":"BLWnre9XXJI"},
    {"date":"2026-04-22","channel":"SBSKPOP X INKIGA...","title":"피디도 놀란 화음 장인들✨ 라이브 요정 리센느의 향기로운 보컬 차력쇼🎶｜리센느(RESCENE) - YoYo｜공간음향🎧라이브｜SoundBOMB360˚[SUB]","cast":"전원","vid":"HQQcWMYZNjc"},
    {"date":"2026-04-22","channel":"SoundBomb360 유튜브...","title":"[보이스캠] 원이 (RESCENE)｜Voice Focused FanCam｜WONI of RESCENE 🎵YoYo｜VoiceCam360˚","cast":"원이","vid":"DwNnB6W8DUE"},
    {"date":"2026-04-22","channel":"SoundBomb360 유튜브...","title":"[보이스캠] 리브 (RESCENE)｜Voice Focused FanCam｜LIV of RESCENE 🎵YoYo｜VoiceCam360˚","cast":"리브","vid":"IO7z1q7qQQc"},
    {"date":"2026-04-22","channel":"SoundBomb360 유튜브...","title":"[보이스캠] 미나미 (RESCENE)｜Voice Focused FanCam｜MINAMI of RESCENE 🎵YoYo｜VoiceCam360˚","cast":"미나미","vid":"2WaRiz5PU7o"},
    {"date":"2026-04-22","channel":"SoundBomb360 유튜브...","title":"[보이스캠] 메이 (RESCENE)｜Voice Focused FanCam｜MAY of RESCENE 🎵YoYo｜VoiceCam360˚","cast":"메이","vid":"YHNopaeAxr8"},
    {"date":"2026-04-22","channel":"SoundBomb360 유튜브...","title":"[보이스캠] 제나 (RESCENE)｜Voice Focused FanCam｜ZENA of RESCENE 🎵YoYo｜VoiceCam360˚","cast":"제나","vid":"qW2ixjRpm9Y"},
    {"date":"2026-04-22","channel":"KBS Kpop","title":"[리무진서비스] EP.211 리센느 미나미 | RESCENE MINAMI | Runaway, 나였으면, My Gospel, Timeless","cast":"미나미[3]","vid":"SW7M6MdlrlU"},
    {"date":"2026-04-20","channel":"K-TIGERS","title":"[텐톡 TentTalk EP.02] 리센느 Rescene | 걸스토크대잔치 #미나미 #메이 #리센느","cast":"미나미, 메이","vid":"_0QMfF7nv1s"},
    {"date":"2026-04-20","channel":"Arirang Radio","title":"RESCENE (리센느) - Runaway | K-Pop Live Session| K-Poppin'","cast":"전원","vid":"WhVH7yAaHy8"},
    {"date":"2026-04-20","channel":"블립","title":"갸루 미나미 \"러쉬 야호~💖\" 당한 만큼 돌려주는 여돌의 러쉬 알바 체험기 ㅋㅋㅋ | 깜짝카메라 | 리센느(RESCENE) | 러쉬 일일알바 | blip originals","cast":"전원","vid":"Nw4BTs2K3X4"},
    {"date":"2026-04-20","channel":"Arirang Radio","title":"Twinkle My Star with RESCENE (리센느)","cast":"전원","vid":"zo2inLqmt64"},
    {"date":"2026-04-17","channel":"스튜디오ㅋㅇㅋ","title":"새신랑된다는 지상렬이 패밀리카 구입하러 찾아왔습니다 (지바겐, 타스만) | 중고생 EP.04","cast":"원이","vid":"9BTgYmDmOEE"},
    {"date":"2026-04-17","channel":"ALL THE K-POP 유튜...","title":"RESCENE - Runaway (리센느 - 런어웨이) | IDOL UNPLUGGED","cast":"전원","vid":"W07b3zKHnL4"},
    {"date":"2026-04-17","channel":"안녕하세요원이입니다잘부탁드립니다","title":"유영우 삼촌과 눈물 참기 대결","cast":"원이","vid":"giWNmOtwsR4"},
    {"date":"2026-04-16","channel":"유튜브 채널","title":"얼마나 귀엽냐면 리센느 들.튀(Runaway) 하고 싶을 정도로 귀여움 | 돌들의침묵 | 리센느(RESCENE) 'Runaway'","cast":"전원","vid":"hW62aZ6-VMA"},
    {"date":"2026-04-16","channel":"유튜브 채널","title":"[4K] RESCENE (리센느) - Runaway | #저스트댄스 #Just_Dance","cast":"전원","vid":"l2SeGMZYCjE"},
    {"date":"2026-04-16","channel":"ALL THE K-POP","title":"RESCENE | IDOL UNPLUGGED | MUSIC TALK","cast":"전원","vid":"caYd7jBfa9U"},
    {"date":"2026-04-15","channel":"꼰대희","title":"[뭐할꼰대EP.12] 리브야 제나야 같이 확마! Runaway 해뿌까! (feat. 리센느)","cast":"리브, 제나","vid":"PYzVqgqS09g"},
    {"date":"2026-04-15","channel":"wowkoreanfan","title":"리센느(RESCENE), 디지털 싱글 앨범 'Runaway'를 소개하는 영상 공개!","cast":"전원","vid":"vqbesIlW4O0"},
    {"date":"2026-04-15","channel":"유튜브 채널","title":"[MC석 코너] 친구같은 컴백 인터뷰! ‘영파씨(YOUNG POSSE)&RESCENE(리센느)’ 나!왔어✋🏻 l Show Champion l EP.593 l 260415","cast":"미나미, 메이","vid":"lzG2xjWaOsk"},
    {"date":"2026-04-14","channel":"유튜브 채널","title":"[SUB] 백수 아들에게 장미. 꽃. 한송이. 놓고. 갑니다~^^ | 돌들의침묵 | 리센느(RESCENE) 'Runaway'","cast":"전원","vid":"x8EU50FVB1k"},
    {"date":"2026-04-14","channel":"SBSKPOP X INKIGA...","title":"듣자마자 펼쳐지는 판타지 세계🪄신비로운 소녀들의 몽환 라이브🎤💞리센느(RESCENE)- Runaway | 공간음향🎧라이브 | SoundBOMB360˚[SUB]","cast":"전원","vid":"NAXYoFYjcfk"},
    {"date":"2026-04-14","channel":"SoundBomb360 유튜브...","title":"[보이스캠] 원이 (RESCENE) | Voice Focused FanCam | WONI of RESCENE 🎵Runaway | VoiceCam360˚","cast":"원이","vid":"32pQMFj8AOM"},
    {"date":"2026-04-14","channel":"SoundBomb360 유튜브...","title":"[보이스캠] 리브 (RESCENE)｜Voice Focused FanCam｜LIV of RESCENE 🎵Runaway｜VoiceCam360˚","cast":"리브","vid":"APOshkYdTL0"},
    {"date":"2026-04-14","channel":"SoundBomb360 유튜브...","title":"[보이스캠] 미나미 (RESCENE)｜Voice Focused FanCam｜MINAMI of RESCENE 🎵Runaway｜VoiceCam360˚","cast":"미나미","vid":"8-eWWKqMC8k"},
    {"date":"2026-04-14","channel":"SoundBomb360 유튜브...","title":"[보이스캠] 메이 (RESCENE)｜Voice Focused FanCam｜MAY of RESCENE 🎵Runaway｜VoiceCam360˚","cast":"메이","vid":"FpBCr5TpPqw"},
    {"date":"2026-04-14","channel":"SoundBomb360 유튜브...","title":"[보이스캠] 제나 (RESCENE)｜Voice Focused FanCam｜ZENA of RESCENE 🎵Runaway｜VoiceCam360˚","cast":"제나","vid":"6hJSgkqUVWc"},
    {"date":"2026-04-13","channel":"유튜브 채널","title":"러쉬 얼마나 잘되고싶은지 감도 안옴😇 (멤버 전원 MBTI 다름 주의) | 깜짝카메라 | 리센느(RESCENE) | 기묘한 뷰티샵 | blip originals","cast":"전원","vid":"iGgAH6O4JIs"},
    {"date":"2026-04-13","channel":"유튜브 채널","title":"[4K] RESCENE(리센느) “Runaway” Band LIVE | it's Live","cast":"전원","vid":"aDHmmrfizIE"},
    {"date":"2026-04-13","channel":"M2(엠넷)","title":"[릴레이댄스] 리센느(RESCENE) - Runaway (4K)","cast":"전원","vid":"Q3Uy_6Z2cFo"},
    {"date":"2026-04-13","channel":"Stage Wemake 유튜브...","title":"[KIDS TAKE] RESCENE(리센느) ‘Runaway’ | STAGE WE MAKE | 4K","cast":"전원","vid":"TQzioay9wqo"},
    {"date":"2026-04-11","channel":"Stage Wemake 유튜브...","title":"RESCENE(리센느) ‘Runaway’ | STAGE WE MAKE | 4K","cast":"전원","vid":"f8up3TTw_94"},
    {"date":"2026-04-11","channel":"안녕하세요원이입니다잘부탁드립니다","title":"미나미가 부르는 불량연애 ost","cast":"원이","vid":"xwqUuKRSB2w"},
    {"date":"2026-04-11","channel":"안녕하세요원이입니다잘부탁드립니다","title":"랩 같은 거 안 한다니까","cast":"원이","vid":"Hqv_N2h4Ym4"},
    {"date":"2026-04-10","channel":"스튜디오ㅋㅇㅋ","title":"초보운전이 서울 불지옥 주차장에서 안 긁을 수 있을까?","cast":"원이","vid":"899JRmfaCx8"},
    {"date":"2026-04-10","channel":"코인없는 코인 노래방 유튜브 ...","title":"사라진 소녀들을 노래방에서 찾았습니다🎶 #리센느 EP.87 | 노래방 라이브 코없코","cast":"리브, 미나미, 제나","vid":"npwNcBPw7rg"},
    {"date":"2026-04-10","channel":"안녕하세요원이입니다잘부탁드립니다","title":"루카루카나이트피버","cast":"원이","vid":"P5hyRkrFUSY"},
    {"date":"2026-04-09","channel":"안녕하세요원이입니다잘부탁드립니다","title":"미나미의 갸루라이브 메들리!","cast":"원이, 미나미","vid":"FcMaC8akSU8"},
    {"date":"2026-04-09","channel":"안녕하세요원이입니다잘부탁드립니다","title":"치바갸루와 거제갸루","cast":"원이","vid":"mDwMojRzdD0"},
    {"date":"2026-04-03","channel":"스튜디오ㅋㅇㅋ","title":"초보운전이 테슬라 FSD와 사랑에 빠진 이유","cast":"원이","vid":"zeGThcVvi-U"},
    {"date":"2026-04-02","channel":"별이부르는방에","title":"이번 플레이리스트 기대되는 이유 : 리센느 자장가 있음🫢❣️ | 별이 부르는 방에 | PLAYLIST | 리센느 리브 X 미나미 X 제나 | 4K","cast":"리브, 미나미, 제나","vid":"5Whlkurz0-E"},
    {"date":"2026-04-01","channel":"안녕하세요원이입니다잘부탁드립니다","title":"파인다이닝 주문하는 법","cast":"원이","vid":"F6PzIVMxrEQ"},
    {"date":"2026-04-01","channel":"안녕하세요원이입니다잘부탁드립니다","title":"최종 가격은?","cast":"원이","vid":"IWlKNWGim2o"},
    {"date":"2026-03-31","channel":"PBLive","title":"ちゃんみな-SAD SONG Covered by RESCENE／PBLive","cast":"전원","vid":"FUhkv2YZxnc"},
    {"date":"2026-03-31","channel":"PBLive","title":"【舞台裏密着】RESCENE","cast":"전원","vid":"SoxMWDZ7JXw"},
    {"date":"2026-03-31","channel":"별이부르는방에","title":"🎶리센느 자장가 동결건조하면 안될까? 영원히 듣고 싶어...🧊 (EN/JP/KR) | 별이 부르는 방에 | 리센느 리브 X 미나미 X 제나 | 4K","cast":"리브, 미나미, 제나","vid":"waTiGXeIRJE"},
    {"date":"2026-03-30","channel":"PBLive","title":"RESCENE_LOVE ATTACK／PBLive","cast":"전원","vid":"B444RNWb-u0"},
    {"date":"2026-03-29","channel":"유튜브 채널","title":"[SUB] EP.60 RESCENE | 봄에는 피크닉이지🥪 근데 뭘 먹을지는 비밀이야🤫 | 돌박이일 #리센느 봄 소풍 투어 [4K]","cast":"전원","vid":"LgcegoGS41k"},
    {"date":"2026-03-29","channel":"PBLive","title":"RESCENE Voice Mail/PBLive","cast":"전원","vid":"KLIdXB5MC9s"},
    {"date":"2026-03-29","channel":"안녕하세요원이입니다잘부탁드립니다","title":"인생 첫 파인다이닝에 간 셋","cast":"원이","vid":"inaTPJiZ734"},
    {"date":"2026-03-27","channel":"스튜디오ㅋㅇㅋ","title":"컴백 전 카니발 타고 나들이 좀 다녀왔습니다 (리센느 멤버 전원 출격)","cast":"전원","vid":"2ej7jEBCJnQ"},
    {"date":"2026-03-26","channel":"제일건강합니다","title":"아이돌 대기실에 급습한 탄수화물 중독자 | 제일건강합니다 EP.02","cast":"전원","vid":"LlMJTeXoe6E"},
    {"date":"2026-03-26","channel":"Anniversary","title":"[RESCENE HAPPY 2nd ANNIVERSARY] FAKE RE:SCENE ㅣ 리센느, 학교에 가다?!🏫","cast":"전원","vid":"WkUINlol-OY"},
    {"date":"2026-03-22","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갸루로 변하는 과정","cast":"원이","vid":"jesKrPOh9aE"},
    {"date":"2026-03-22","channel":"안녕하세요원이입니다잘부탁드립니다","title":"퀸의 마인드","cast":"원이","vid":"lIqwLsFw3LQ"},
    {"date":"2026-03-21","channel":"안녕하세요원이입니다잘부탁드립니다","title":"추워도 견뎌라","cast":"원이","vid":"9lZ49H7koy8"},
    {"date":"2026-03-21","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갸루가 말하는 방법","cast":"원이","vid":"sjxwELcdu1s"},
    {"date":"2026-03-20","channel":"스튜디오ㅋㅇㅋ","title":"레이에 20인치 휠 달고 팝콘 소리 터트릴 수 있나요?","cast":"원이","vid":"YmG80DphBgE"},
    {"date":"2026-03-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갸루의 자세에 대해서 배워보았습니다","cast":"원이, 미나미","vid":"heifaIjlSUc"},
    {"date":"2026-03-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"한국에 놀러왔어요","cast":"원이","vid":"LWOehrdWzD8"},
    {"date":"2026-03-19","channel":"justicebateria 유...","title":"MINAMI (미나미) X JUSTICEBACTERIA - Losing You (Original by FLO)","cast":"미나미","vid":"nBWg9eWMbfc"},
    {"date":"2026-03-18","channel":"팬더원","title":"OFF Air☕ | 난 리센느가 좋아💖RESCENE와의 𝐓𝐀𝐋𝐊","cast":"전원","vid":"8RnNpl1ndJk"},
    {"date":"2026-03-18","channel":"Re-log","title":"[Re-log] 먹짱 원짱 😋🍽️ | RESCENE (리센느) vlog","cast":"전원","vid":"r17X1HWHxsM"},
    {"date":"2026-03-18","channel":"팬더원","title":"OFF Air☕BEHIND | 꾸밈없는 대답을 리마인이 원해💖RESCENE CUT","cast":"전원","vid":"PbzLUakw2BE"},
    {"date":"2026-03-16","channel":"덬마니 유튜브 썸네일","title":"[돈룩백 몰아보기] 전원 비주얼 걸그룹 리센느는 가방에 뭘 들고 다닐까? | RESCENE | Don't Look BAG 합본","cast":"전원","vid":"bubnFseL05k"},
    {"date":"2026-03-14","channel":"스튜디오ㅋㅇㅋ","title":"리센느 대표님은 멘탈이 완전히 나가버렸습니다","cast":"원이","vid":"--QzVnSp-UI"},
    {"date":"2026-03-11","channel":"Re-log","title":"[Re-log] LIV’s Bertie Bott's Every Flavour Beans Taste Test🍬 | RESCENE (리센느) vlog","cast":"전원","vid":"uJ_MG1I_6MU"},
    {"date":"2026-03-09","channel":"유튜브 채널","title":"[덕질캡처용♥CLEAN] RESCENE - Busy Boy l Show Champion l EP.587","cast":"전원","vid":"ylD2Lskwydw"},
    {"date":"2026-03-08","channel":"안녕하세요원이입니다잘부탁드립니다","title":"일본인 한국인 구분법","cast":"원이","vid":"WdMdgQJPDmw"},
    {"date":"2026-03-08","channel":"안녕하세요원이입니다잘부탁드립니다","title":"머리가 이게 뭐야","cast":"원이","vid":"p64_9aBYqLk"},
    {"date":"2026-03-07","channel":"안녕하세요원이입니다잘부탁드립니다","title":"일본어의 3가지 모드","cast":"원이","vid":"zhW1dc6TiZU"},
    {"date":"2026-03-07","channel":"안녕하세요원이입니다잘부탁드립니다","title":"바로 번역가능한 로봇 출시","cast":"원이","vid":"2bwRDVLzho4"},
    {"date":"2026-03-07","channel":"안녕하세요원이입니다잘부탁드립니다","title":"\"그 눈빛\"","cast":"원이","vid":"ragd7gVdtRk"},
    {"date":"2026-03-07","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갸루의 부작용","cast":"원이","vid":"QXisYCiUJwc"},
    {"date":"2026-03-06","channel":"나의 연수 아저씨","title":"명현만에게 패배하고 귀농을 위해 포터2 구매하러 온 줄리엔강 | 중고생 EP.03","cast":"전원","vid":"rMfoWvneX4o"},
    {"date":"2026-03-06","channel":"안녕하세요원이입니다잘부탁드립니다","title":"갸루 출신 일본인에게 일본어 배우기","cast":"원이, 미나미","vid":"bvUS-ri9nqQ"},
    {"date":"2026-03-04","channel":"Re-log","title":"[Re-log] 까엉티비 🐹 | RESCENE (리센느) vlog","cast":"전원","vid":"RiBPfWXPS9Y"},
    {"date":"2026-02-27","channel":"나의 연수 아저씨","title":"선민 영우 삼촌과 떠나는 새벽 일탈 풀코스","cast":"전원","vid":"RPP-Vvsnfo4"},
    {"date":"2026-02-27","channel":"안녕하세요원이입니다잘부탁드립니다","title":"인간에게 가장 위험한 동물 TOP 5 (사망률 기준)","cast":"원이","vid":"ZLWqgD03tFU"},
    {"date":"2026-02-27","channel":"안녕하세요원이입니다잘부탁드립니다","title":"인간을 가장 많이 죽인 동물은?","cast":"원이","vid":"UoEqF2_aIJk"},
    {"date":"2026-02-25","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) I-SHA 렌즈 광고 Behind","cast":"전원","vid":"wf7AR9GsZsk"},
    {"date":"2026-02-23","channel":"안녕하세요원이입니다잘부탁드립니다","title":"우리가 몰랐던 놀라운 사실","cast":"원이","vid":"JPKJA5UCkiA"},
    {"date":"2026-02-20","channel":"나의 연수 아저씨","title":"춘봉이, 첨지, 칠복이의 운전기사 송하빈 | 중고생 EP.02","cast":"전원","vid":"dDesySmyTUA"},
    {"date":"2026-02-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"정일영 교수님과 달팽이 요리","cast":"원이","vid":"1O4hJxumimA"},
    {"date":"2026-02-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"공황장애 치료법","cast":"원이","vid":"EVJyBi45blE"},
    {"date":"2026-02-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"봉쥬르 하는 방법","cast":"원이","vid":"2bwRDVLzho4"},
    {"date":"2026-02-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"나오라고 하면 됩니다","cast":"원이","vid":"8VN-5OxoTMc"},
    {"date":"2026-02-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"프랑스에서 아이돌이 나오기 힘든 이유","cast":"원이","vid":"C7nJvm6j7d8"},
    {"date":"2026-02-20","channel":"안녕하세요원이입니다잘부탁드립니다","title":"소매치기에서 살아남는 법","cast":"원이","vid":"hZn6Yb6M6oM"},
    {"date":"2026-02-19","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 2025 인천공항 SKY FESTIVAL Behind","cast":"전원","vid":"u-2SUo7p_vI"},
    {"date":"2026-02-17","channel":"Special Clip","title":"[Special Clip] RESCENE(리센느) 2026 설 인사 영상","cast":"전원","vid":"B47O9OcvCXA"},
    {"date":"2026-02-13","channel":"덬마니 유튜브 썸네일","title":"[돈룩백] 여권 사진부터 공주 아이템까지👑 예능감 미친 걸그룹 리센느의 멤버 가방 털기 타임👜 | RESCENE | Don't Look BAG EP.1-2","cast":"전원","vid":"CCBGSoJlFvE"},
    {"date":"2026-02-13","channel":"나의 연수 아저씨","title":"원이랑 운전 연수 할 사람?[1]","cast":"전원","vid":"CdCTblZ6TBs"},
    {"date":"2026-02-11","channel":"Re:Creation","title":"[Re:Creation] 함께 꾸며요🎀 신년 맞이 메이의 다이어리 꾸미기📒✨ | RESCENE (리센느)","cast":"전원","vid":"fZIZYl6QMYQ"},
    {"date":"2026-02-11","channel":"한국청소년연맹","title":"[4K] 홍보대사 RESCENE(리센느) | Glow Up | 아람단 | 촬영스케치 | 코야티비","cast":"전원","vid":"xx7MyFWM12o"},
    {"date":"2026-02-10","channel":"안녕하세요원이입니다잘부탁드립니다","title":"곰을 만났을 때 대처법 (실전편)","cast":"원이","vid":"6sIeZF5_ixU"},
    {"date":"2026-02-10","channel":"안녕하세요원이입니다잘부탁드립니다","title":"곰을 만났을 때 대처법 (상상편)","cast":"원이","vid":"fbgmOeTkKHw"},
    {"date":"2026-02-10","channel":"안녕하세요원이입니다잘부탁드립니다","title":"곰을 만났을때 대처법","cast":"원이","vid":"FvGQHwTrDuA"},
    {"date":"2026-02-08","channel":"eastifyofficial ...","title":"EASTIFY Radio // An Interview with RESCENE","cast":"원이, 리브, 미나미, 제나","vid":"gWBk65FsS0c"},
    {"date":"2026-02-07","channel":"안녕하세요원이입니다잘부탁드립니다","title":"이선민 급습 컨텐츠는 진짜일까?","cast":"원이","vid":"_Lz7eFNbDGI"},
    {"date":"2026-02-06","channel":"스튜디오ㅋㅇㅋ","title":"주차 스트레스 많이 받을거야","cast":"원이","vid":"ALL7wNu1oV8"},
    {"date":"2026-02-06","channel":"안녕하세요원이입니다잘부탁드립니다","title":"선민 삼촌과 콩나물 국밥","cast":"원이","vid":"lSxqQYipZoU"},
    {"date":"2026-02-06","channel":"안녕하세요원이입니다잘부탁드립니다","title":"이선민을 울리는 방법","cast":"원이","vid":"7yX9Zm5EU-w"},
    {"date":"2026-02-06","channel":"안녕하세요원이입니다잘부탁드립니다","title":"전설의 캐릭터","cast":"원이","vid":"3HEz0AoDPlc"},
    {"date":"2026-02-06","channel":"안녕하세요원이입니다잘부탁드립니다","title":"제가 섭외하고 싶은 게스트는요","cast":"원이","vid":"MJNJs0_cgUs"},
    {"date":"2026-02-06","channel":"안녕하세요원이입니다잘부탁드립니다","title":"삼촌 우리 성공해요","cast":"원이","vid":"-w54l3NkWQQ"},
    {"date":"2026-02-05","channel":"덬마니 유튜브 썸네일","title":"[돈룩백] 걸그룹 찐템 탈탈 털었습니다✨ 리센느의 노필터 노컨셉 가방 공개 타임👜 | RESCENE | Don't Look BAG EP.1-1","cast":"전원","vid":"bBusIXfjyvI"},
    {"date":"2026-02-04","channel":"Re-log","title":"[Re-log] 미나미의 휴가 브이로그 in JAPAN 🏠 | RESCENE (리센느) vlog","cast":"전원","vid":"97YE7zPrON8"},
    {"date":"2026-01-30","channel":"스튜디오ㅋㅇㅋ","title":"본인 구속보다 빠른 중고차 구입하러 온 유희관 | 중고생 EP.01","cast":"원이","vid":"OEo-LuPR0xQ"},
    {"date":"2026-01-30","channel":"Re-log","title":"[Re-log] JAPAN Convenience Store 🍨 | RESCENE (리센느) vlog","cast":"전원","vid":"UhgtuFEIAys"},
    {"date":"2026-01-29","channel":"KBS WORLD TV 유튜브...","title":"[4K HFR] RESCENE's [마이데이트립 My Daytrip to Jeongseon] EP02 | KBS WORLD TV 260130","cast":"원이, 미나미","vid":"MYXmkxiFc54"},
    {"date":"2026-01-24","channel":"기타","title":"어질어질 시작된 공놀이 게임 🏓 | 리센느 운동회 | RESCENE (리센느)","cast":"전원","vid":"o4ZB_NVoCuw"},
    {"date":"2026-01-23","channel":"스튜디오ㅋㅇㅋ","title":"배우 이선민 출근길 습격","cast":"원이","vid":"w3PWN_xnLKU-g8"},
    {"date":"2026-01-23","channel":"나의 연수 아저씨","title":"배우 이선민 출근길 습격","cast":"전원","vid":"w3PWN_xnLKU"},
    {"date":"2026-01-22","channel":"KBS WORLD TV 유튜브...","title":"[4K HFR] RESCENE's [마이데이트립 My Daytrip to Jeongseon] EP01 | KBS WORLD TV 260123","cast":"원이, 미나미","vid":"jEieMUq7iXY"},
    {"date":"2026-01-22","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 'Bloom' 음악방송 챌린지 Behind","cast":"전원","vid":"vDt7xQkCCtM"},
    {"date":"2026-01-16","channel":"스튜디오ㅋㅇㅋ","title":"경차로 떠난 거제 풀코스 여행","cast":"원이","vid":"aFhYXNCn-g8"},
    {"date":"2026-01-16","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 'Heart Drop' 음악방송 챌린지 Behind","cast":"전원","vid":"FehXr6GSRKo"},
    {"date":"2026-01-15","channel":"핸드볼H리그","title":"이제는 화장품 매장까지 꾸민다고?🫢 | 핸드볼 선수&아이돌 리센느 프리티스킨 매·꾸 대결💄","cast":"미나미, 메이","vid":"vMmi0ler84k"},
    {"date":"2026-01-12","channel":"BASE NOTES","title":"왔다 리마인들의 두쫀쿠🧆 | RESCENE (리센느) ‘Bloom’ 음악방송 Behind #2","cast":"전원","vid":"1cxLn6elYn0"},
    {"date":"2026-01-07","channel":"BASE NOTES","title":"더 아름답게 피어나지💐 | RESCENE (리센느) ‘Bloom’ 음악방송 Behind #1","cast":"전원","vid":"nxR4my5whlU"},
    {"date":"2026-01-05","channel":"iM뱅크","title":"복지가 별거냐? 원이 & 리브 얼굴이 곧 복지;; 대한민국 알고리즘 점령한 역주행 아이돌의 대명사 리센느(with. 숏박스 김원훈 & 개그콘서트 나현영) ㅣ iM파인다이닝 EP.3","cast":"원이, 리브","vid":"zdv19CZ1ILI"},
    {"date":"2026-01-05","channel":"BASE NOTES","title":"우리 오늘 좀 멋있을지도 몰라~ 😎 | RESCENE (리센느) 'lip bomb' Showcase Behind","cast":"전원","vid":"TD9f8ymdq14"},
    {"date":"2026-01-04","channel":"Que Lunes RNT 유튜...","title":"El Año nuevo llega con @RESCENE_official , Han Hyejin y @VIVANATIVA","cast":"원이, 리브, 미나미, 제나","vid":"xMNQA_yonyo"},
    {"date":"2026-01-04","channel":"KAvenyou","title":"[INTERVIEW] The girls of RESCENE discuss lip bomb & special messages for fans in Singapore!","cast":"원이, 리브, 미나미, 제나","vid":"2PAusbMWDrg"},
    {"date":"2026-01-02","channel":"스튜디오ㅋㅇㅋ","title":"초보운전이 내비 없이 왕복 8시간 거제까지 갈 수 있을까?","cast":"원이","vid":"RAdzJewQUs0"},
    {"date":"2025-12-31","channel":"라이온 뮤직","title":"미나미 / RESCENE(리센느) - Love Echo, MVP, Bloom | Live Clip | 4K | LionMusic","cast":"미나미","vid":"otmyfnOeolo"},
    {"date":"2025-12-31","channel":"BASE NOTES","title":"왕 크니까 왕 귀엽잖아...?!🫢 | RESCENE (리센느) 'Heart Drop' 음악방송 Behind","cast":"전원","vid":"iV3UtGz3JKU"},
    {"date":"2025-12-29","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 'Bloom' Recording Behind","cast":"전원","vid":"oVC1aQDDoGI"},
    {"date":"2025-12-28","channel":"KOCCA MUSIC 유튜브 ...","title":"\"[리센느‘s Pick: My Songs] RESCENE(리센느) 멤버들이 직접 뽑은 '찐' 최애곡 모음 | 내선내곡 | Car!Plist 겨울편 Ep.2","cast":"전원","vid":"j8GVTYbCv7Q"},
    {"date":"2025-12-27","channel":"KOCCA MUSIC 유튜브 ...","title":"𝑷𝒍𝒂𝒚𝒍𝒊𝒔𝒕 | 겨울, RESCENE(리센느)가 선곡한 핫팩 플레이리스트 | Car!Plist 겨울편 Ep.2","cast":"리브, 미나미, 제나","vid":"k6BmYs-MRkI"},
    {"date":"2025-12-26","channel":"KOCCA MUSIC 유튜브 ...","title":"내 플리는 RESCENE(리센느)로 가득해🌿 리브,미나미,제나의 최애곡과 함께한 드라이브 | Car!Plist 겨울편 Ep.2 리센느 [EN/ES]","cast":"리브, 미나미, 제나","vid":"iAfkK5Cb6_M"},
    {"date":"2025-12-25","channel":"Special Clip","title":"[Special Clip] RESCENE(리센느) 2025 크리스마스 인사ㅣChristmas Message 💌","cast":"전원","vid":"Krqqjcs6188"},
    {"date":"2025-12-23","channel":"Stage Wemake 유튜브...","title":"[X-mas] RESCENE (리센느) | STAGE WE MAKE","cast":"전원","vid":"4Q2pn7Fz-P0"},
    {"date":"2025-12-18","channel":"FOX 13 Seattle p...","title":"RESCENE opens up about expectations, teamwork, and their latest album","cast":"전원","vid":"L0lWn3umTjg"},
    {"date":"2025-12-13","channel":"덕질은과학이다 프로필","title":"힙합보단 사랑 사랑보단 취미, 난 펠트 인형이나 만들래~♪ | 취미명세서 EP.13 | 의뢰인 리센느 원이&메이","cast":"원이, 메이","vid":"lh7E2_zoZIU"},
    {"date":"2025-12-13","channel":"BASE NOTES","title":"센둥이들 동물의 숲에 놀러 오신 걸 환영 합니다🤗 | RESCENE (리센느) 'Bloom' MV Behind","cast":"전원","vid":"DT8fJqmk8fY"},
    {"date":"2025-12-12","channel":"스튜디오ㅋㅇㅋ","title":"초보운전 3개월 만에 800만원짜리 첫 차 질렀습니다","cast":"원이","vid":"k3SHr4Cvkk0"},
    {"date":"2025-12-10","channel":"KFN","title":"[그날군대이야기] 세대를 넘어 사랑 받는 군가 이야기 |국방홍보원 @kfnplus","cast":"리브","vid":"1IaUAqgaO60"},
    {"date":"2025-12-05","channel":"스튜디오ㅋㅇㅋ","title":"초보운전이 뽑은 운전 중 가장 빡치는 최악의 빌런은?","cast":"원이","vid":"HamNe9Fntew"},
    {"date":"2025-12-05","channel":"BASE NOTES","title":"마늘 아니고🧄 메이ㄹㅏㄱㅜ...😤ㅣRESCENE (리센느) 'lip bomb' Jacket Photoshoot Behind","cast":"전원","vid":"JdqQpNg9LP0"},
    {"date":"2025-12-03","channel":"Stage Wemake 유튜브...","title":"[ONE TAKE] RESCENE(리센느) ‘Bloom’ | STAGE WE MAKE | 4K","cast":"전원","vid":"GtjX3iUnuY0"},
    {"date":"2025-12-02","channel":"Stage Wemake 유튜브...","title":"RESCENE(리센느) ‘Bloom’ | STAGE WE MAKE | 4K","cast":"전원","vid":"WvYkfxAWpYo"},
    {"date":"2025-12-01","channel":"Stage Wemake 유튜브...","title":"(Teaser) RESCENE(리센느) ‘Bloom’ | STAGE WE MAKE | 4K","cast":"전원","vid":"6X0ftgGOGzM"},
    {"date":"2025-11-29","channel":"Anniversary","title":"생각이 많을 땐💡 미나미 브이로그지🎁 ㅣ MINAMI HBD TO ME🎂ㅣMINAMI’s B-Day Vlog","cast":"전원","vid":"N1WckPLsJ3k"},
    {"date":"2025-11-28","channel":"1theK Originals ...","title":"RESCENE(리센느) ‘Bloom' | On the Spot | 온더스팟","cast":"전원","vid":"kjvlrGs5f7c"},
    {"date":"2025-11-27","channel":"샤랄라스튜디오","title":"왔다 내 최애 향수, 리센느 완전체 등판! #리센느 EP.72 | 코없코","cast":"전원","vid":"NQC2VZbHo-E"},
    {"date":"2025-11-27","channel":"Anniversary","title":"제나의 생일 어드벤처🎡ㅣ ZENA HBD TO ME🎂ㅣZENA’s B-Day Vlog","cast":"전원","vid":"W6F7n8DDgnk"},
    {"date":"2025-11-26","channel":"유튜브 채널","title":"[릴레이댄스] 리센느(RESCENE) - Bloom (4K)","cast":"전원","vid":"sXecMQuWyOo"},
    {"date":"2025-11-25","channel":"퍼스널 Personal 유튜브...","title":"[𝘾𝙪𝙧𝙖𝙩𝙚𝙙 𝙗𝙮 𝙍𝙀𝙎𝘾𝙀𝙉𝙀] 리센느가 직접 선곡한 리센느 향기 가득한 플레이리스트💄💕 | 3rd Mini [lip bomb] | Heart Drop, Bloom","cast":"전원","vid":"y9SKSzvrGaw"},
    {"date":"2025-11-23","channel":"The Artist Canav...","title":"((Off Shot) RESCENE (리센느) - Heart Dropㅣ오픈 캔버스","cast":"전원","vid":"oY_DaS06dlo"},
    {"date":"2025-11-22","channel":"The Artist Canav...","title":"RESCENE (리센느) - Heart Dropㅣ오픈 캔버스ㅣ4KㅣThe Artist Canvas","cast":"전원","vid":"WgDRLNgzztU"},
    {"date":"2025-11-21","channel":"벨리곰 TV","title":"길을 묻는 전학생이 존예 아이돌이었다면? RESCENE 원이 편","cast":"원이","vid":"X0AWk7EITLE"},
    {"date":"2025-11-21","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 'Heart Drop' Recording Behind","cast":"전원","vid":"doGCcKx9F1Q"},
    {"date":"2025-11-19","channel":"KFN","title":"[그날군대이야기] 우리가 반드시 기억해야 할 영웅, 소년병 |국방홍보원 @kfnplus","cast":"리브","vid":"fUojhdXjziM"},
    {"date":"2025-11-14","channel":"스튜디오ㅋㅇㅋ","title":"이선민 삼촌의 스포티지(Old)로 첫 셀프 세차","cast":"원이","vid":"RwQPrwx4GdQ"},
    {"date":"2025-11-14","channel":"BASE NOTES","title":"우리 막내가 벌써 운전을?! 🚗 | RESCENE (리센느) 'Heart Drop' MV Behind","cast":"전원","vid":"mw9lpLi_HJA"},
    {"date":"2025-11-12","channel":"Special Clip","title":"[Special Clip] RESCENE(리센느) 2026년 수능 응원 영상","cast":"전원","vid":"kxJNpgmfWjE"},
    {"date":"2025-11-10","channel":"유튜브 채널","title":"[릴레이댄스] 리센느(RESCENE) - Heart Drop (4K)","cast":"전원","vid":"Yxb6ZCxac9o"},
    {"date":"2025-10-28","channel":"The Artist Canav...","title":"(Behind The Scenes) RESCENE (리센느) - 고백주파수ㅣ오픈 캔버스ㅣ4KㅣThe Artist Canvas","cast":"전원","vid":"SGmC-YuOWyM"},
    {"date":"2025-10-27","channel":"The Artist Canav...","title":"RESCENE (리센느) - 고백주파수ㅣ오픈 캔버스ㅣ4KㅣThe Artist Canvas","cast":"전원","vid":"p1asr5bLsl0"},
    {"date":"2025-10-26","channel":"The Artist Canav...","title":"(Teaser) RESCENE (리센느) - 고백주파수ㅣ오픈 캔버스ㅣ4KㅣThe Artist Canvas","cast":"전원","vid":"7ykC1JAdCr8"},
    {"date":"2025-10-24","channel":"스튜디오ㅋㅇㅋ","title":"아이오닉 왜 타요? 첫 전기차 운전하는 면허 2달 차","cast":"원이","vid":"OgzZei1v22M"},
    {"date":"2025-10-24","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 2025 RESCENE 1st FAN-CON in TAIPEI : RE:MIND 본공연 Behind","cast":"전원","vid":"uec8lTxOV6k"},
    {"date":"2025-10-17","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 전북특별자치도민체육대회 개회식 공연 Behind","cast":"전원","vid":"vwsH71lpyG4"},
    {"date":"2025-10-11","channel":"Anniversary","title":"🎀오늘은 리브 하고 싶은 거 다 해🎂ㅣ LIV HBD TO ME🎂ㅣLIV B-Day Vlog","cast":"전원","vid":"O623FzKis10"},
    {"date":"2025-10-10","channel":"스튜디오ㅋㅇㅋ","title":"을왕리 드라이브 중 접촉사고 날 뻔한 면허 1달차","cast":"원이","vid":"r5B1ZUu3VrE"},
    {"date":"2025-10-06","channel":"Special Clip","title":"[Special Clip] RESCENE(리센느) 2025 추석 인사 영상","cast":"전원","vid":"G-tdsyfG90M"},
    {"date":"2025-09-26","channel":"아이돌백스테이지","title":"[리센느] “네오, 마지막 교신” - 리센느가 전하는 진심 💌 | #05","cast":"전원","vid":"wlfyyIK0be8"},
    {"date":"2025-09-26","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 요코하마 & 나고야 공연 Behind","cast":"전원","vid":"wfrXzdw1SR4"},
    {"date":"2025-09-19","channel":"스튜디오ㅋㅇㅋ","title":"BMW 3시리즈 타고 풀악셀 밟는 면허 1일차","cast":"원이","vid":"vi-4XTy-Sl8"},
    {"date":"2025-09-19","channel":"by RESCENE","title":"미나미 (MINAMI) 'TITANIUM' COVER (원곡: David Guetta)","cast":"전원","vid":"AhJb7wPiOjQ"},
    {"date":"2025-09-18","channel":"유튜브 채널","title":"[4K] the Fillin' Live ep 28. RESCENE(리센느) | it's Live","cast":"전원","vid":"nQSBOVxs_YY"},
    {"date":"2025-09-17","channel":"유튜브 채널","title":"[Official] RESCENE (리센느) - 고백주파수 Special Clip","cast":"전원","vid":"Ihsh9VRZLlo"},
    {"date":"2025-09-12","channel":"유튜브 채널","title":"Got The Spot in Gangnam [4K] (CHN, IDN, JPN, MYS Sub) EP04 | KBS WORLD TV 20250912","cast":"미나미","vid":"WSO76DcpAOw"},
    {"date":"2025-09-12","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 2025 RESCENE X ELITE 엘리트 학생복 촬영 Behind","cast":"전원","vid":"9fEfAacMpDE"},
    {"date":"2025-09-08","channel":"유튜브 채널","title":"2025 뉴시스 한류엑스포 가수 리센느 인터뷰","cast":"전원","vid":"d4psisZDWpg"},
    {"date":"2025-09-05","channel":"유튜브 채널","title":"Got The Spot in Gangnam [4K] (CHN, IDN, JPN, MYS Sub) EP03 | KBS WORLD TV 20250905","cast":"미나미","vid":"nqiY3q8E80M"},
    {"date":"2025-09-05","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 2025 RESCENE 1st FAN-CON : Project 326 본공연 Behind","cast":"전원","vid":"YfrsyCN30rs"},
    {"date":"2025-09-02","channel":"팬바타 FANVATAR(202...","title":"(SUB) | 리센느 먹짱 알고리즘 대공개! | RESCENE 팬바타 Q&A (ENG/JPN/IDN/SPA)","cast":"전원","vid":"8y5egW-5f3Y"},
    {"date":"2025-08-30","channel":"유튜브 채널","title":"[SPOTLIGHT Rookies] Ep.46 RESCENE(리센느)","cast":"전원","vid":"pDBwqYIAyf8"},
    {"date":"2025-08-29","channel":"유튜브 채널","title":"Got the Spot in Gangnam [4K] (CHN, IDN, MYS Sub) EP02 | KBS WORLD TV 20250829","cast":"미나미","vid":"7xhmgCasD2I"},
    {"date":"2025-08-29","channel":"스튜디오ㅋㅇㅋ","title":"\"필기시험을 떨어졌다고?\" 무면허 아이돌과 운전 연수(feat. 폭스바겐 골프)","cast":"원이","vid":"FkzlNowaWOY"},
    {"date":"2025-08-29","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE (리센느) 2025 RESCENE 1st FAN-CON : Project 326 VCR 촬영 Behind","cast":"전원","vid":"D0hHQRTADII"},
    {"date":"2025-08-28","channel":"아이돌백스테이지","title":"[리센느] 알고보면 아직 소녀소녀🌼 결국 눈물 터진 막내들😥 | #02","cast":"전원","vid":"6q76zd38izM"},
    {"date":"2025-08-25","channel":"유튜브 채널","title":"지우상점 OPEN🎀 츄꾸미들 만나서 하룰라라 갔다 옴 🧚💖","cast":"전원","vid":"Zg7MO20jQHU"},
    {"date":"2025-08-24","channel":"유튜브 채널","title":"Got the Spot in Gangnam [4K] (CHN, IDN, MYS Sub) EP01 | KBS WORLD TV 20250823","cast":"미나미","vid":"pymJqRX1fN8"},
    {"date":"2025-08-24","channel":"유튜브 채널","title":"[I am 제나] 중학교 2학년 때 서바이벌 도전한 소녀, 리센느의 황금막내로","cast":"제나","vid":"NKDjYnV4Wcc"},
    {"date":"2025-08-22","channel":"FrontRowLiveEnt","title":"RESCENE (리센느) 인터뷰 | 'Dearest' & 'Glow Up' EP 제작 과정","cast":"전원","vid":"TbwtzAtdcQk"},
    {"date":"2025-08-21","channel":"아이돌백스테이지","title":"[리센느] 집밥은 못 참지🔥 제나 엄마찬스! 폭주하는 리센느에 회사는 그저 바라볼수밖에...😨 | #01","cast":"전원","vid":"pHYC8bO6B2o"},
    {"date":"2025-08-21","channel":"2025 RESCENE 1st FAN-CON : Project 326","title":"Playlist 🎧 | 2025 RESCENE 1st FAN-CON : Project 326","cast":"전원","vid":"qAdGlDfw7_U"},
    {"date":"2025-08-21","channel":"기타","title":"RESCENE (리센느) Official Character Teaser","cast":"전원","vid":"1Jms0oQkL2k"},
    {"date":"2025-08-19","channel":"Anniversary","title":"오늘은 메이를 위한 하루 ✨ㅣMAY HBD TO ME🎂ㅣMAY's B-Day Vlog","cast":"전원","vid":"G2QpiBYo7Pc"},
    {"date":"2025-08-18","channel":"2025 RESCENE 1st FAN-CON : Project 326","title":"RESCENE(리센느) | 'UhUh (Dance Break Ver.)' @ 2025 RESCENE 1st FAN-CON : Project 326","cast":"전원","vid":"vCkkkE7ktes"},
    {"date":"2025-08-18","channel":"2025 RESCENE 1st FAN-CON : Project 326","title":"RESCENE(리센느) | '중독 (Overdose) Cover' @ 2025 RESCENE 1st FAN-CON : Project 326","cast":"전원","vid":"HVsMGlboV_s"},
    {"date":"2025-08-15","channel":"스튜디오ㅋㅇㅋ","title":"현대차도 모르는데 운전을 어떻게 해","cast":"원이","vid":"0MDOY5m-Xa4"},
    {"date":"2025-08-14","channel":"아이돌백스테이지","title":"(예고편) 무대 뒤에서 만난 신인 여돌 리센느의 리얼한 일상! 🎥 | 아이돌 백스테이지","cast":"전원","vid":"x-R-9B894-E"},
    {"date":"2025-08-14","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 홍콩공연 Behind","cast":"전원","vid":"bTLbLf2z8pQ"},
    {"date":"2025-08-13","channel":"스튜디오ㅋㅇㅋ","title":"운전 연수 해주실 분?","cast":"원이","vid":"6pMUeLI4hAM"},
    {"date":"2025-08-13","channel":"2025 RESCENE 1st FAN-CON : Project 326","title":"RESCENE(리센느) | ‘중독 (Overdose) Cover’ Dance Practice ver. @ 2025 RESCENE 1st FAN-CON : Project 326","cast":"전원","vid":"e8CfO3CwiGI"},
    {"date":"2025-08-12","channel":"팬바타 FANVATAR(202...","title":"(SUB) | 항상 준비가 된 리센느의 노래 자랑🎤 | RESCENE 우리 노래를 들어줘 (ENG/JPN/IDN/SPA)","cast":"전원","vid":"vxZF9CHkCMI"},
    {"date":"2025-08-08","channel":"깡시안","title":"자신이 없어요, 질 자신이 (feat. 허벅지 씨름) | [깡시안] EP1","cast":"전원","vid":"3OjtAzZxGng"},
    {"date":"2025-08-08","channel":"by RESCENE","title":"HAPPY – DAY6 | Cover by Gyubin(규빈) X MINAMI of RESCENE","cast":"전원","vid":"TucLh-PYwwE"},
    {"date":"2025-08-06","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Mood' Recording Behind","cast":"전원","vid":"UC1s-yWK1Dk"},
    {"date":"2025-08-04","channel":"엠뚜루마뚜루 프로필 사진","title":"[복면가왕] 국적 의심스럽게 하는 한국어 실력🫰 스테이씨도 입덕한 다재다능 리센느 메인보컬 미나미🩷 | #미나미 #리센느 MBC250803방송","cast":"미나미","vid":"9LnzP7fXUS0"},
    {"date":"2025-08-02","channel":"유튜브 채널","title":"[I am 미나미] \"한국어 패치 완료\".. 중학생 때 걸그룹 서바이벌 도전했던 일본 소녀, 압도적 성장","cast":"미나미","vid":"v7U7O3O9-JE"},
    {"date":"2025-08-01","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 2025 RESCENE 1st FAN-CON : Project 326 포스터 촬영 Behind","cast":"전원","vid":"cFOAGLZNFCg"},
    {"date":"2025-07-31","channel":"우정잉","title":"현직 걸그룹에게 배우는 직캠 필살기 [리센느 초대석]","cast":"리브, 미나미, 제나","vid":"fHi9yZNLJVQ"},
    {"date":"2025-07-24","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Deja Vu' Recording Behind","cast":"전원","vid":"Gt9GpU1yMWk"},
    {"date":"2025-07-23","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Deja Vu' 음악방송 Behind","cast":"전원","vid":"gSDodK69puY"},
    {"date":"2025-07-18","channel":"아이컨택 스튜디오","title":"귀엽고 예쁘고 노래 잘하고 좋은 건 다 하는 리센느! 그녀들을 응원하는 대선배님의 등장까지 I EP. 06 [벤80도]","cast":"전원","vid":"Wu9cKzV0ERQ"},
    {"date":"2025-07-18","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Deja Vu' MV Behind","cast":"전원","vid":"EeHhcBwq0hQ"},
    {"date":"2025-07-17","channel":"유튜브 채널","title":"안녕 우리 리센느가 장기자랑에서 뭐 보여줄 게 있다 하거든? | 돌들의침묵 | 리센느(RESCENE) 'Deja Vu'","cast":"전원","vid":"X0THv6jY69g"},
    {"date":"2025-07-16","channel":"유튜브 채널","title":"이건 두 번째 레슨... 리센느가 알려주는 환경보건 센스도 너만 갖기!","cast":"리브, 미나미, 메이, 제나","vid":"kkIpV70p9Yo"},
    {"date":"2025-07-16","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Dearest' Jacket Photoshoot Behind","cast":"전원","vid":"edszA3S4eRs"},
    {"date":"2025-07-14","channel":"아이돌 한국어 프로필","title":"[Ep.600] w/ 리센느 RESCENE 💌 빌리의 아이돌 사랑방 💌","cast":"리브, 미나미, 메이, 제나","vid":"9Ct1B5lxfy4"},
    {"date":"2025-07-11","channel":"by RESCENE","title":"꽃길 - 김세정 | Cover by Gyubin(규빈) X MINAMI of RESCENE","cast":"전원","vid":"FzUeh7XBOmI"},
    {"date":"2025-07-09","channel":"유튜브 채널","title":"이건 첫 번째 레슨… 리센느 면접썰, 너만 알기!","cast":"리브, 미나미, 메이, 제나","vid":"o8YKcfTnorE"},
    {"date":"2025-07-07","channel":"유튜브 채널","title":"[아두럽] 첫사랑 비주얼에 그렇지 못한 리센느 입담🧚‍♀️ 방귀 소리가 가장 귀여운 멤버는? 🤭 | IDOL DKDK CLUB - RESCENE","cast":"전원","vid":"mjUekIjNJ0w"},
    {"date":"2025-07-06","channel":"유튜브 채널","title":"[릴레이댄스] 리센느(RESCENE) - Deja Vu (4K)","cast":"전원","vid":"tyN8SszsRtQ"},
    {"date":"2025-07-05","channel":"1theK Originals ...","title":"리센느 내돌차보고 하룰라라 궁전 갈 사람~😇☁️ | RESCENE (리센느) | Deja Vu | 내돌의 온도차 | GAP CRUSH","cast":"전원","vid":"yhEmbt_PWys"},
    {"date":"2025-07-04","channel":"유튜브 채널","title":"[ALLIVE] RESCENE -Twinkle(원곡: 소녀시대 태티서) | 올라이브 | 정오의 희망곡 김신영입니다｜MBC 250704 방송","cast":"리브, 미나미, 제나","vid":"iQmR7Rn1BgU"},
    {"date":"2025-07-04","channel":"팬바타 FANVATAR","title":"(SUB) | 리센느의 풀향 가득한 Deja Vu..🌿 | RESCENE 인터뷰 (ENG/JPN/IDN/SPA)","cast":"전원","vid":"sgqL6AUMyQs"},
    {"date":"2025-07-03","channel":"전파상사","title":"역주행의 신화 리센느 모셨습니다✨ l 전파상사 ep.70","cast":"전원","vid":"rirxHEHs1Rw"},
    {"date":"2025-07-02","channel":"유튜브 채널","title":"RESCENE(리센느) 음악엔 좋은 향이 나요 🌸☺️ㅣSpotify Super Rookie","cast":"전원","vid":"2VT7VGZckHw"},
    {"date":"2025-06-28","channel":"유후","title":"요즘 핫한 걸그룹 '리센느' 미나미님 초대석!!! 개이쁨 ㄷㄷ;","cast":"미나미","vid":"IGSdLavpcwE"},
    {"date":"2025-06-27","channel":"ten title","title":"🚀상처폭격기 미나미 & 원이 | 판까지 마.피아 with. 유희관, 리센느 | 배성재의 텐 | 20250627","cast":"원이, 미나미","vid":"Q7pWeKFbWgU"},
    {"date":"2025-06-26","channel":"KBS WORLD TV 유튜브...","title":"MV DREAM (뮤비드림) [4K HDR] (CHN, IDN, JPN, MYS Sub) RESCENE (리센느) EP03 | KBS WORLD TV 250626","cast":"전원","vid":"5kKFPPlfG3c"},
    {"date":"2025-06-21","channel":"정다쌤과 아이들","title":"초등학생이 부르는 RESCENE(리센느) ‘LOVE ATTACK’ 풀버전 #리센느 #러브어택 #콜라보","cast":"전원","vid":"q3p6-8H6Rrw"},
    {"date":"2025-06-19","channel":"KBS WORLD TV 유튜브...","title":"MV DREAM (뮤비드림) [4K HDR] (CHN, IDN, JPN, MYS Sub) RESCENE (리센느) EP02 | KBS WORLD TV 20250619","cast":"전원","vid":"uPNlC5gXGWQ"},
    {"date":"2025-06-16","channel":"by RESCENE","title":"RESCENE(리센느) '마지막처럼' Dance Practice (원곡: BLACKPINK)","cast":"전원","vid":"rVPh9-CtmiA"},
    {"date":"2025-06-14","channel":"Re:Creation","title":"[Re:Creation] 리센느 전원일기 EP.03 🍀| RESCENE(리센느)","cast":"전원","vid":"Qz5c8QVnsFU"},
    {"date":"2025-06-13","channel":"KBS WORLD TV 유튜브...","title":"MV DREAM (뮤비드림) [4K HDR] (CHN, IDN, JPN, MYS Sub) RESCENE EP01 | KBS WORLD TV 20250613","cast":"전원","vid":"5Uoc0sHfdn0"},
    {"date":"2025-06-12","channel":"Re:Creation","title":"[Re:Creation] 리센느 전원일기 EP.02 🍀| RESCENE(리센느)","cast":"전원","vid":"wyTLakQ1Fdg"},
    {"date":"2025-06-05","channel":"Re:Creation","title":"[Re:Creation] 리센느 전원일기 EP.01 🍀| RESCENE(리센느)","cast":"전원","vid":"GV_6frhuxPs"},
    {"date":"2025-05-28","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) KCON JAPAN 2025 Behind","cast":"전원","vid":"uuCBqyINkhw"},
    {"date":"2025-05-25","channel":"샤랄라스튜디오","title":"💿RESCENE(리센느) - LOVE ATTACK｜코없코 1hour","cast":"리브, 미나미","vid":"qrToX9N2698"},
    {"date":"2025-05-25","channel":"Anniversary","title":"오늘만큼은, 나를 위한 시간 🎁ㅣWONI HBD TO ME🎂ㅣW:One Day Vlog","cast":"전원","vid":"yPRYmyMw4g0"},
    {"date":"2025-05-23","channel":"유튜브 채널","title":"⭐ SHOWCASE | RESCENE(리센느) | KCON JAPAN 2025","cast":"전원","vid":"Ep5_5JrKIOQ"},
    {"date":"2025-05-21","channel":"유튜브 채널","title":"⭐ PRESHOW | RESCENE (리센느) | KCON JAPAN 2025","cast":"전원","vid":"yFfKimbDrqo"},
    {"date":"2025-05-16","channel":"팬바타 FANVATAR(202...","title":"(SUB) I 리센느의 햇살 메이가 뺏고 싶은 파트 최초 공개(?) | RESCENE Q&A (ENG/JPN/IDN/SPA)","cast":"전원","vid":"szfa39EHtGM"},
    {"date":"2025-05-14","channel":"유튜브 채널","title":"와~ 리센느다..! | 승리요정 리센느 비하인드캠📷","cast":"전원","vid":"c31jPOG_d-s"},
    {"date":"2025-05-13","channel":"딩고 뮤직","title":"100秒で聞くリセンヌ (RESCENE) [100sec] Glow Up(EN Ver.), UhUh(JP Vers.), YoYo(JP Vers.), Love attack | dingo","cast":"전원","vid":"4-BYDjk5EsI"},
    {"date":"2025-05-09","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 키움 히어로즈 시구 Behind","cast":"전원","vid":"rQ143lRSSd4"},
    {"date":"2025-05-06","channel":"딩고 뮤직","title":"RESCENE - YoYo (Japanese Version) | [TEXTED] Minami | 歌詞紙 (Lyrics) | dingo japan","cast":"미나미","vid":"Lle0xkhk_9M"},
    {"date":"2025-04-30","channel":"기타","title":"𝗥𝗘𝗦𝗖𝗘𝗡𝗘 𝗣𝗟𝗔𝗬𝗟𝗜𝗦𝗧 | 풀냄새 맡았더니 나도 모르게 플레이 누름🌿 | 리센느가 풀밭에서 추천한 노래들💿","cast":"전원","vid":"xeEMSoqKfBY"},
    {"date":"2025-04-29","channel":"유튜브 채널","title":"SERINA's MakeUp Tutorial Ep.02 COOL한 아기 호랑이 등장이요 🐯🌟 FEAT - #MINAMI of #RESCENE","cast":"미나미","vid":"RkfGMeNl7g0"},
    {"date":"2025-04-28","channel":"컴백홈","title":"RESCENE(리센느) - 'Glow up' + 'LOVE ATTACK' (4K) perfomance l 1+1원플원","cast":"전원","vid":"QS3wqBNQ-pw"},
    {"date":"2025-04-25","channel":"키움 히어로즈","title":"생애 첫 시구 #메이 #리센느 #리브ㅣ시구 비하인드 (04.20)","cast":"전원","vid":"mCKfVw65JuE"},
    {"date":"2025-04-23","channel":"헤이데이heyday","title":"실시간 역주행의 주인공, 1년차 신인 걸그룹 \"리센느\"의 하루! (Love attack)","cast":"전원","vid":"B6j2hBBRd28"},
    {"date":"2025-04-18","channel":"by RESCENE","title":"ZENA(제나) 'Life's Too Short' COVER (원곡:aespa) Photo Booth Ver.","cast":"전원","vid":"OybCC65kqEw"},
    {"date":"2025-04-16","channel":"유튜브 채널","title":"가광 초대석, 누구세요? with RESCENE(리센느) full ver. / [이은지의 가요광장] I KBS 250416 방송","cast":"전원","vid":"1EYMmNL0iTw"},
    {"date":"2025-04-11","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 일본 도쿄 공연 모음.zip","cast":"전원","vid":"5gUixjcMne8"},
    {"date":"2025-04-02","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 2024 대구 한국가스공사 페가수스 시투 Behind","cast":"전원","vid":"D2bd-ABAbPo"},
    {"date":"2025-04-01","channel":"by RESCENE","title":"MINAMI(미나미) 'Dry Flower' COVER (원곡: Yuuri)","cast":"전원","vid":"i0UW8-8UCvc"},
    {"date":"2025-03-31","channel":"유튜브 채널","title":"[아이CONTACT] RESCENE(리센느) ‘LOVE ATTACK’ | Off The Stage | 4K","cast":"전원","vid":"6kYsRRXtHhE"},
    {"date":"2025-03-30","channel":"유튜브 채널","title":"RESCENE(리센느) ‘LOVE ATTACK’ | Performance | Off The Stage | 4K","cast":"전원","vid":"QeK0Bx7RYdQ"},
    {"date":"2025-03-26","channel":"Anniversary","title":"[RESCENE HAPPY 1st ANNIVERSARY] FAKE RE:SCENE ㅣ 리센느, 연습생으로 돌아가다?!","cast":"전원","vid":"Wa7Cs87L7SU"},
    {"date":"2025-03-22","channel":"뭉트니스","title":"다이어트 끝! 치팅 시작! 걸그룹의 먹방","cast":"리브, 제나, 미나미","vid":"HmRkIKdRAxI"},
    {"date":"2025-03-22","channel":"유튜브 채널","title":"룩삼의 들어볼래 MUZZK 뮤지직 ep.7 🎤🎵🎼 (wt.케인/플레임/리센느)","cast":"전원","vid":null},
    {"date":"2025-03-19","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 2024 광주 FC 축하공연 Behind","cast":"전원","vid":"ZzwlwioKwjk"},
    {"date":"2025-03-15","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 2024 아시아 모델 어워즈 Behind","cast":"전원","vid":"FaNaH1a1c3k"},
    {"date":"2025-03-07","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Glow Up' MV Behind","cast":"전원","vid":"860263NHDAI"},
    {"date":"2025-03-05","channel":"마젠타","title":"일본 귀족이 평가하는 QWER...","cast":"미나미","vid":"xbbPXlzDTCs"},
    {"date":"2025-03-05","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Glow Up' Showcase Behind","cast":"전원","vid":"zCdmGbkZDwo"},
    {"date":"2025-03-03","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Glow Up' 음악방송 Behind","cast":"전원","vid":"voJbMfriFbI"},
    {"date":"2025-03-01","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Glow Up' JACKET & TRAILER Behind #2","cast":"전원","vid":"EicUPexKEDE"},
    {"date":"2025-02-27","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Glow Up' JACKET & TRAILER Behind #1","cast":"전원","vid":"ZcOIlhAih38"},
    {"date":"2025-02-24","channel":"Arirang Radio","title":"노래에서 향이 나요 𝑅𝐸𝒮𝒞𝐸𝒩𝐸🌸│ #리센느 몰아보기👀 │ #심플리콘투어","cast":"전원","vid":"OSTU90FPU0I"},
    {"date":"2025-02-24","channel":"Arirang Radio","title":"Keyword Interview with RESCENE : What's their choice?","cast":"전원","vid":"BnYYkUQefJQ"},
    {"date":"2025-02-24","channel":"Arirang Radio","title":"RESCENE (리센느) - Glow Up | K-Pop Live Session | K-Poppin'","cast":"전원","vid":"YsPHUlAQkUg"},
    {"date":"2025-02-24","channel":"Arirang Radio","title":"RESCENE (리센느) - CRASH | K-Pop Live Session | K-Poppin'","cast":"전원","vid":"4iZUV00c8s8"},
    {"date":"2025-02-24","channel":"BASE NOTES","title":"RESCENE(리센느) 'Glow Up' Recording Behind","cast":"전원","vid":"QEkzEM_kJCI"},
    {"date":"2025-02-21","channel":"유튜브 채널","title":"[생로덕질의 비밀] 숨은 뇌세포를 깨워주는 아이돌이 있다?! 🧠 | 리센느(RESCENE) | blip originals","cast":"전원","vid":"1a37e5GWMUM"},
    {"date":"2025-02-17","channel":"유튜브 채널","title":"(ENG) '공주의 품격’ 문제 못 맞히면 조금 곤란해~👑 | 덕력고사(Fandom Level Test) | 리센느(RESCENE) | 블립 오리지널 | blip originals","cast":"전원","vid":"fHa0Mtxb31A"},
    {"date":"2025-02-17","channel":"유튜브 채널","title":"[FULL] EP#98 리센느의 성장일지✍💕️｜아이돌 라디오(IDOL RADIO) 시즌4｜MBC 250217 방송","cast":"전원","vid":null},
    {"date":"2025-02-14","channel":"팬바타 FANVATAR(202...","title":"(SUB) | 리센느의 가장 빛났던 순간✨ | RESCENE 백일장(ENG/JPN/IDN/SPA)","cast":"전원","vid":"nczUUW6OiTg"},
    {"date":"2025-02-13","channel":"유튜브 채널","title":"리센느(RESCENE)는 아트박스에서 뭘 살까?👀 | 팬들을 위한 Glow Up한 선물 고르기✨ | 🎁구독자 이벤트","cast":"전원","vid":"GNTiMc85VTY"},
    {"date":"2025-02-12","channel":"유튜브 채널","title":"[MC석 코너] 취향이 선명해지는 시간✨ 'RESCENE' 취향의 발견💖 l Show Champion l EP.543 l 250212","cast":"전원","vid":"dkIHyNMJg3c"},
    {"date":"2025-02-12","channel":"유튜브 채널","title":"[FULL] 음색 천재만재 그룹 ✨RESCENE(리센느)✨와 친친에서 Glow Up🫧 할 시간💙 | 친한친구 이현입니다 | MBC 250212 방송","cast":"전원","vid":null},
    {"date":"2025-02-11","channel":"유튜브 채널","title":"[4K] 홍보대사 RESCENE(리센느) | Glow Up | 아람단 | 촬영스케치 | 코야티비","cast":"전원","vid":"xx7MyFWM12o"},
    {"date":"2025-02-11","channel":"팬바타 FANVATAR","title":"(SUB) | 리센느에게 가는 길은 언제나 Glow Up✨ | RESCENE 인터뷰(ENG/JPN/IDN/SPA)","cast":"전원","vid":"h75PA-VgUG4"},
    {"date":"2025-02-09","channel":"유튜브 채널","title":"[릴레이댄스] 리센느(RESCENE) - Glow Up (4K)","cast":"전원","vid":"HaC6XZRjpXc"},
    {"date":"2025-02-07","channel":"유튜브 채널","title":"[꼬꼬플] 그런데..그 때 아이돌이 핸드크림을 나눠가지자며 다가온거야 🫧 | 리센느(RESCENE) | blip originals","cast":"전원","vid":"1i8ghNiKOOU"},
    {"date":"2025-02-06","channel":"유튜브 채널","title":"[4K] RESCENE(리센느) “Glow Up” Band LIVE Concert 어디서 비누향 안 나요?🫧 [it’s KPOP LIVE 잇츠라이브]","cast":"전원","vid":"6zJRA5U-gq0"},
    {"date":"2025-02-04","channel":"뭉트니스","title":"단기간 다이어트, 가능한가? 리센느 컴백 준비🔥","cast":"리브, 제나, 미나미","vid":"rTPwkLKoqC4"},
    {"date":"2025-02-03","channel":"유튜브 채널","title":"리센느 다음 컨셉은 두리안이 함께하는 과일바구니?!🍊 | 챌린지 위드 미|리센느(RESCENE) | 블립 오리지널 | blip originals","cast":"전원","vid":"cKa8yd73YFQ"},
    {"date":"2025-01-28","channel":"Special Clip","title":"[Special Clip] RESCENE(리센느) 2025 설 인사 영상","cast":"전원","vid":"zCOAQMADQyY"},
    {"date":"2025-01-17","channel":"Re:Creation","title":"[Re:Creation] 리센느 꾸미기 #3 👚 | EP.3 - RESCENE(리센느)","cast":"전원","vid":"pYMr28ESeGM"},
    {"date":"2025-01-15","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'APT.' Special Performance Behind","cast":"전원","vid":"nQiNK7p6Ohs"},
    {"date":"2025-01-13","channel":"Re:Creation","title":"[Re:Creation] 리센느 꾸미기 #2 👚 | EP.2 - RESCENE(리센느)","cast":"전원","vid":"adFSoJAc2yg"},
    {"date":"2025-01-10","channel":"ten title","title":"🤔묘하게 이상한데 웃긴 리센느 리브 & 원이 & 메이 | 신인 대전! 프로듀스1077 | RESCENE | 배성재의 텐 20250110","cast":"원이, 리브, 메이","vid":"QI4o-1Z9p_s"},
    {"date":"2025-01-08","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 일본 팝업 스토어 방문 Behind","cast":"전원","vid":"_dUcpB9CgaY"},
    {"date":"2025-01-06","channel":"유튜브 채널","title":"[2024 Best Challenge] 마루는 강쥐부터 옴브리뉴까지! 2024년을 뜨겁게 달군 챌린지 스페셜🔥 | iPhone16Pro (4K)","cast":"원이, 미나미","vid":"5a-t-JjN2hA"},
    {"date":"2025-01-05","channel":"스튜디오슈붕","title":"[웰투동 EP.04] 윤수빈 아나운서한테 도전장 내미는 아이돌 (feat. 리센느, 방주호)","cast":"원이, 미나미","vid":"JHySJFgdahU"},
    {"date":"2024-12-28","channel":"하이픽션","title":"인질 역할에 아이돌이 왔다 (feat. 리센느)","cast":"전원","vid":"37tje2u7SZ8"},
    {"date":"2024-12-27","channel":"Re-log","title":"[Re-log] in LA📸 #3 | RESCENE(리센느) vlog","cast":"전원","vid":"-qG8y0p2Zds"},
    {"date":"2024-12-25","channel":"국민방송 CI 상하","title":"[도시직썰 외전] 김시덕 박사와 리센느 미나미가 만난 증평의 사람들~ 특집 도시직썰 2편!","cast":"미나미","vid":"Ge-nX5VE28A"},
    {"date":"2024-12-25","channel":"Special Clip","title":"[Special Clip] RESCENE(리센느) 2024 크리스마스 인사| Christmas Message 💌","cast":"전원","vid":"m_UqbdJV5T8"},
    {"date":"2024-12-24","channel":"유튜브 채널","title":"[릴레이댄스] 2024 Special I aespa부터 G-DRAGON까지! 2024년을 뜨겁게 달군 K-POP 스페셜 릴댄🔥 (4K)","cast":"원이, 미나미","vid":"mKW6PsitCSQ"},
    {"date":"2024-12-24","channel":"by RESCENE","title":"RESCENE(리센느) 'Underneath the Tree' Special Live","cast":"전원","vid":"Ocby704Ou-E"},
    {"date":"2024-12-23","channel":"Re:Creation","title":"[Re:Creation] 리센느 꾸미기 #1 👚 | EP.1 - RESCENE(리센느)","cast":"전원","vid":"t37nR21Str8"},
    {"date":"2024-12-14","channel":"국민방송 CI 상하","title":"[도시직썰 외전] 증평군. 이곳에 대한민국 지역이 살아날 해법이 숨어있다?! 지역이 가야할 길을 제시하는 콤팩트 시티.","cast":"미나미","vid":"UWBzwqcb9tI"},
    {"date":"2024-12-09","channel":"Re-log","title":"[Re-log] in LA📸 #2 | RESCENE(리센느) vlog","cast":"전원","vid":"qCstak0tYos"},
    {"date":"2024-11-27","channel":"기타","title":"RESCENE(리센느) 실버 버튼 언박싱 ASMR","cast":"전원","vid":"OQcGGTAGXgE"},
    {"date":"2024-11-21","channel":"Re-log","title":"[Re-log] in LA📸 #1 | RESCENE(리센느) vlog","cast":"전원","vid":"qDUkVfrcWJs"},
    {"date":"2024-11-18","channel":"돈가파","title":"2024 최고의 라이징 스타 리센느와 프로그램 흑백요리사의 콜라보? / 리센느 빠다를 이겨라","cast":"전원","vid":"ip8k2pM_GOU"},
    {"date":"2024-11-18","channel":"by RESCENE","title":"RESCENE(리센느) 'APT.' Special Performance","cast":"전원","vid":"_3Wp8i5dfJs"},
    {"date":"2024-11-13","channel":"Special Clip","title":"[Special Clip] RESCENE(리센느) 2025년 수능 응원 영상","cast":"전원","vid":"Vj2jNxFqong"},
    {"date":"2024-11-11","channel":"돈가파","title":"\"저희 좀 키워주세요~\" DGP엔터테인먼트를 찾아온 라이징 스타 리센느","cast":"전원","vid":"r0aBwvfiNjY"},
    {"date":"2024-11-06","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 대학교 축제 Behind","cast":"전원","vid":"MdExOs06el4"},
    {"date":"2024-10-30","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Pinball' 음악방송 Behind","cast":"전원","vid":"YExvIec1mtw"},
    {"date":"2024-10-29","channel":"Cinescape","title":"Desde Corea: Las chicas de RESCENE nos cuentan TODO sobre su nuevo éxito","cast":"전원","vid":"LjF3e4IJc4c"},
    {"date":"2024-10-23","channel":"KOREANET","title":"💓 Feeling love attack 👊 | K-POP STAR SHOWCASE | Ep.81 RESCENE","cast":"전원","vid":"WojiC2ZPpk8"},
    {"date":"2024-10-23","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 삼성 라이온즈 시구 Behind","cast":"전원","vid":"qOjBSaXFcIg"},
    {"date":"2024-10-23","channel":"KOREANET","title":"💓 Feeling love attack 👊 | K-POP STAR SHOWCASE | Ep.81 RESCENE","cast":"전원","vid":"WojiC2ZPpk8I"},
    {"date":"2024-10-22","channel":"딩고 뮤직","title":"[180VR] RESCENE(리센느)-LOVE ATTACK l 3D PERFORMANCE VIDEO l MOVE REC ONETAKEㅣ딩고뮤직ㅣDingo Music","cast":"전원","vid":"idW0CiCAdfk"},
    {"date":"2024-10-19","channel":"detikcom","title":"Serangan 'LOVE ATTACK' RESCENE (ENG/INA SUB)","cast":"전원","vid":"p8tKDo9q024"},
    {"date":"2024-10-17","channel":"피지컬갤러리","title":"러닝크루에 함부로 들어가면 안되는 이유","cast":"원이","vid":"If2kxD44R8A"},
    {"date":"2024-10-16","channel":"KOREANET","title":"[4K] RESCENE LIV | K-pop Star Showcase | MVP FanCam | FULL VER","cast":"리브","vid":"guiFwLRcFS0"},
    {"date":"2024-10-14","channel":"wowkoreanfan","title":"[4K] 리센느(RESCENE), 일본에서 단독 인터뷰 진행...'항상 응원해주시는 팬 여러분 사랑해요~'","cast":"전원","vid":"cAKXNGUi8B0"},
    {"date":"2024-10-10","channel":"유튜브 채널","title":"[Simply K-Pop CON-TOUR] Preview with RESCENE (리센느) _ Ep.635","cast":"전원","vid":"B1Eau0aBYkY"},
    {"date":"2024-10-09","channel":"딩고 뮤직","title":"RESCENE(리센느) – Pinball | dingo live | 딩고뮤직 | Dingo Music","cast":"전원","vid":"cxgqZqo14EA"},
    {"date":"2024-10-04","channel":"딩고 뮤직","title":"[라이징댄스] LUN8(루네이트), RESCENE(리센느), NOWADAYS(나우어데이즈)ㅣ딩고뮤직ㅣDingo Music","cast":"제나","vid":"4XoeevrIGaA"},
    {"date":"2024-10-04","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'Pinball' MV Behind","cast":"전원","vid":"VeLrKottXZI"},
    {"date":"2024-09-23","channel":"Arirang Radio","title":"K-Star & Live with RESCENE. Their music shows their story & Amazing Live.","cast":"전원","vid":"i7jSnzRA8UI"},
    {"date":"2024-09-22","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'LOVE ATTACK' MV Behind Part 2","cast":"전원","vid":"lAHkez2DvwA"},
    {"date":"2024-09-20","channel":"Arirang Radio","title":"[4K] RESCENE(리센느) - 'New World' _ EP.632","cast":"전원","vid":"WwGF_sqjH6c"},
    {"date":"2024-09-14","channel":"STATV","title":"뮤비Pick 'NewPick' RESCENE (리센느) 편","cast":"전원","vid":"6xi9TvHrEQg"},
    {"date":"2024-09-13","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'LOVE ATTACK' MV Behind Part 1","cast":"전원","vid":"ZSk-lj7jX2k"},
    {"date":"2024-09-11","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'SCENEDROME' TRAILER : The beginning Behind","cast":"전원","vid":"BowmAWNKCKI"},
    {"date":"2024-09-09","channel":"딩고 뮤직","title":"[라이징보이스] YOUNG POSSE(영파씨), 리센느(RESCENE) | 딩고뮤직 | DingoMusic","cast":"리브, 미나미","vid":"oSK9blwG864"},
    {"date":"2024-09-07","channel":"유튜브 채널","title":"[4K] RESCENE(리센느) “LOVE ATTACK” Band LIVE Concert 리센느와 잇라는 완벽하게 어울려💘 [it’s KPOP LIVE 잇츠라이브]","cast":"전원","vid":"KRpt7OF4zso"},
    {"date":"2024-09-06","channel":"팬바타 FANVATAR(202...","title":"(SUB) I 리센느가 리더 언니에게 영원히 애교를 부리는 이유는? (ENG/JPN/IDN/SPA)","cast":"전원","vid":"g3KGWcqlnVA"},
    {"date":"2024-09-06","channel":"BASE NOTES","title":"RESCENE(리센느) 'LOVE ATTACK' Recording Behind","cast":"전원","vid":"Cx8tXFPXZqk"},
    {"date":"2024-09-04","channel":"1theK Originals ...","title":"[LIVE] RESCENE(리센느) _ LOVE ATTACK | dancEAR | 댄스이어 | 라이브 퍼포먼스 | Live Performance | 4K","cast":"전원","vid":"hpuepug5RsI"},
    {"date":"2024-09-04","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) 'SCENEDROME' Jacket Photoshoot Behind","cast":"전원","vid":"cGosWWgsNjs"},
    {"date":"2024-09-01","channel":"유튜브 채널","title":"[릴레이댄스] RESCENE(리센느)- LOVE ATTACK (4K)","cast":"전원","vid":"4knUMoDhueo"},
    {"date":"2024-08-30","channel":"팬바타 FANVATAR(202...","title":"(SUB) I 걸음마다 눈부신 리센느의 LOVE ATTACK 💘ㅣRESCENE 인터뷰 (ENG/JPN/IDN/SPA)","cast":"전원","vid":"6RAlVZ0SnHQ"},
    {"date":"2024-08-30","channel":"DGG","title":"RESCENE(리센느)- LOVE ATTACK I COLOR DANCE UNIT |4K Dance Performance DGG| DINGO","cast":"전원","vid":"Yh6nG6UwBUg"},
    {"date":"2024-08-29","channel":"샤랄라스튜디오","title":"🌟06즈 노래방으로 모여라! #리센느 #리브 #미나미 EP.23 | 코없코","cast":"리브, 미나미","vid":"qToKAUYETJI"},
    {"date":"2024-08-29","channel":"유튜브 채널","title":"리센느, 비주얼 향기로 모교 접수하다!💘ㅣ리센느(RESCENE) ㅣ 오우학 EP.11","cast":"전원","vid":"f94PG5sprsc"},
    {"date":"2024-08-28","channel":"DGG","title":"RESCENE(리센느) – LOVE ATTACK | COLOR DANCE | 4K Dance Performance | DGG | DINGO","cast":"전원","vid":"9IcjhTavfqQ"},
    {"date":"2024-07-06","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE 'Re:Scene' #7🌺","cast":"전원","vid":"Nt-3cv0OfkE"},
    {"date":"2024-06-13","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE 'Re:Scene' #6🌺","cast":"전원","vid":"1UKFjyIIyFs"},
    {"date":"2024-05-20","channel":"유튜브 채널","title":"20240501 전부노래잘함 RESCENE 리센느 - 고민중독 (UhUh YoYo 리믹스 버전)","cast":"전원","vid":"3dR0v6i1k40"},
    {"date":"2024-05-16","channel":"유튜브 채널","title":"[4K] RESCENE(리센느) “YoYo” Band LIVE Concert 리센느의 향기에 취할 시간🌺 [it’s KPOP LIVE 잇츠라이브]","cast":"전원","vid":"sJ-ODnxkf8A"},
    {"date":"2024-05-15","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE(리센느) ‘Re:Scene’ Debut Showcase Behind 🌺","cast":"전원","vid":"duurQm9NmHk"},
    {"date":"2024-05-12","channel":"유튜브 채널","title":"[SUB] 리센느가 말하는 데이트룩💕 공감ㅋㅋㅋ 썸잘알(?) 08년생이 쉿-🤫한 이유는?ㅣIDOL24ㅣRESCENE","cast":"전원","vid":"wCyN0is3eyI"},
    {"date":"2024-05-12","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE 'Re:Scene' #5 🌺","cast":"전원","vid":"ML00Fu86B9M"},
    {"date":"2024-05-11","channel":"Documentary ‘THE SCENT’","title":"Documentary ‘THE SCENT’ EP.4 ‘Scent of memory'","cast":"전원","vid":"b1EJ3YqTAwk"},
    {"date":"2024-05-09","channel":"Arirang Radio","title":"Today’s Subject RESCENE at Music Lab [DJ Ashley's Radio' Clock]","cast":"전원","vid":"NNcBZaJQg1I"},
    {"date":"2024-05-09","channel":"BASE NOTES","title":"[BASE NOTES] ‘Re:Scene’ Jacket Making Film 🌺","cast":"전원","vid":"EMoQrQfPF5M"},
    {"date":"2024-05-08","channel":"유튜브 채널","title":"[SUB] RESCENE(리센느), 전원 비주얼 여돌 🚨핫데뷔🚨 고삼차로 수련하는 산독기 신인 어떤데? 👊ㅣ동방으로 따라와ㅣRESCENE","cast":"전원","vid":"aiDpyP2ng3U"},
    {"date":"2024-05-08","channel":"Arirang Radio","title":"[Live] RESCENE (리센느) - UhUh [DJ Ashley's Radio' Clock]","cast":"전원","vid":"B4JSgVh2Dc0"},
    {"date":"2024-05-08","channel":"Arirang Radio","title":"[Live] RESCENE (리센느) - YoYo [DJ Ashley's Radio' Clock]","cast":"전원","vid":"_GHDLCVpYLM"},
    {"date":"2024-05-07","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE 'Re:Scene' #4 🌺","cast":"전원","vid":"IN5Vnej9UhI"},
    {"date":"2024-05-04","channel":"Documentary ‘THE SCENT’","title":"Documentary ‘THE SCENT’ EP.3 ‘Anemoia'","cast":"전원","vid":"b-x8O2jyDkk"},
    {"date":"2024-05-02","channel":"유튜브 채널","title":"🌸 RESCENE 🌼 K-Food Scramble: Guess the K-Pop Song and Dance to Get Your Favorite Food!","cast":"전원","vid":"D5T_lnCNElA"},
    {"date":"2024-05-02","channel":"BASE NOTES","title":"[BASE NOTES] 'YoYo' MV 비하인드 널 위한 Fantasy〰🦋","cast":"전원","vid":"LLMU9CaF9yI"},
    {"date":"2024-04-30","channel":"BASE NOTES","title":"[BASE NOTES] 'UhUh' Special Performance Video Behind🌺","cast":"전원","vid":"7F3L7R6bZBA"},
    {"date":"2024-04-27","channel":"Documentary ‘THE SCENT’","title":"Documentary ‘THE SCENT’ EP.2 ‘Base note'","cast":"전원","vid":"80GGat88Xzs"},
    {"date":"2024-04-26","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE 'Re:Scene' #3 🌺","cast":"전원","vid":"bqEAFISE7hc"},
    {"date":"2024-04-23","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE 'Re:Scene' #2 🌺","cast":"전원","vid":"rDCQNWWWkE0"},
    {"date":"2024-04-20","channel":"Documentary ‘THE SCENT’","title":"Documentary ‘THE SCENT’ EP.1 ‘Unscented'","cast":"전원","vid":"yzbCEI4ua8o"},
    {"date":"2024-04-19","channel":"BASE NOTES","title":"[BASE NOTES] 'UhUh' MV 비하인드 원한다면 Follow me➰🌺 EP.2","cast":"전원","vid":"cLqqjNDqWMg"},
    {"date":"2024-04-19","channel":"Documentary ‘THE SCENT’","title":"RESCENE(리센느) Documentary ‘THE SCENT’ Teaser","cast":"전원","vid":"UwzQFY0eo_A"},
    {"date":"2024-04-07","channel":"BASE NOTES","title":"[BASE NOTES] 'UhUh' MV 비하인드 원한다면 Follow me➰🌺 EP.1","cast":"전원","vid":"HIP4sp40Awo"},
    {"date":"2024-04-06","channel":"BASE NOTES","title":"[BASE NOTES] RESCENE 'Re:Scene' #1 🌺","cast":"전원","vid":"4j81hTzk178"},
    {"date":"2024-03-28","channel":"1theK Originals ...","title":"🌼리센느 내돌차 사건🌼 리센느가 귀염뽀짝 미모폭발로 내돌차를 부순 사건이다 | RESCENE | Uh Uh | 내돌의 온도차 | GAP CRUSH","cast":"전원","vid":"JUiGo7SKE0c"}
];
